/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// The type of hash function used to create the proof, must be one of:
///   * sha512_256
///   * sha256
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Hashtype {}

impl Hashtype {
    /// Default constructor for Hashtype
    pub fn new() -> Hashtype {
        Hashtype::default()
    }
}
