/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// \[apan\] defines the what additional actions occur with the transaction.
///
/// Valid types:
///   * noop
///   * optin
///   * closeout
///   * clear
///   * update
///   * update
///   * delete
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnCompletion {}

impl OnCompletion {
    /// Default constructor for OnCompletion
    pub fn new() -> OnCompletion {
        OnCompletion::default()
    }
}
