/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Application state delta.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateDelta {}

impl StateDelta {
    /// Default constructor for StateDelta
    pub fn new() -> StateDelta {
        StateDelta::default()
    }
}
