/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Represents a key-value store for use in an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealKeyValueStore {}

impl TealKeyValueStore {
    /// Default constructor for TealKeyValueStore
    pub fn new() -> TealKeyValueStore {
        TealKeyValueStore::default()
    }
}
