

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import asyncio
import platform
from .algokit_transact_ffi import SignedTransaction
from .algokit_transact_ffi import Transaction
from .algokit_transact_ffi import _UniffiConverterTypeSignedTransaction
from .algokit_transact_ffi import _UniffiConverterTypeTransaction
from .algokit_transact_ffi import _UniffiRustBuffer as _UniffiRustBufferSignedTransaction
from .algokit_transact_ffi import _UniffiRustBuffer as _UniffiRustBufferTransaction

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("algokit_utils_ffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 26
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_algokit_utils_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_algokit_utils_ffi_checksum_func_algod_localnet() != 6253:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_composer_add_payment() != 9188:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_composer_build() != 13184:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_composer_send() != 61263:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transactions() != 55831:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transaction() != 13641:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_method_transactionsignergetter_get_signer() != 50234:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_algokit_utils_ffi_checksum_constructor_composer_new() != 44040:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,_UniffiRustBuffer,_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER,ctypes.c_uint64,ctypes.POINTER(_UniffiForeignFuture),
)
_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD1 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBufferTransaction,_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER,ctypes.c_uint64,ctypes.POINTER(_UniffiForeignFuture),
)
_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_GETTER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.POINTER(_UniffiRustBuffer),
    ctypes.POINTER(_UniffiRustCallStatus),
)
class _UniffiVTableCallbackInterfaceTransactionSigner(ctypes.Structure):
    _fields_ = [
        ("sign_transactions", _UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD0),
        ("sign_transaction", _UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD1),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
class _UniffiVTableCallbackInterfaceTransactionSignerGetter(ctypes.Structure):
    _fields_ = [
        ("get_signer", _UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_GETTER_METHOD0),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_algodclient.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_algodclient.restype = ctypes.c_void_p
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_algodclient.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_algodclient.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_composer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_composer.restype = ctypes.c_void_p
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_composer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_composer.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_constructor_composer_new.argtypes = (
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_constructor_composer_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_add_payment.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_add_payment.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_build.argtypes = (
    ctypes.c_void_p,
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_build.restype = ctypes.c_uint64
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_send.argtypes = (
    ctypes.c_void_p,
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_send.restype = ctypes.c_uint64
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsigner.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsigner.restype = ctypes.c_void_p
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsigner.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsigner.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsigner.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceTransactionSigner),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsigner.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transactions.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transactions.restype = ctypes.c_uint64
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transaction.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBufferTransaction,
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transaction.restype = ctypes.c_uint64
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsignergetter.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsignergetter.restype = ctypes.c_void_p
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsignergetter.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsignergetter.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsignergetter.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceTransactionSignerGetter),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsignergetter.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsignergetter_get_signer.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsignergetter_get_signer.restype = _UniffiRustBuffer
_UniffiLib.uniffi_algokit_utils_ffi_fn_func_algod_localnet.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_algokit_utils_ffi_fn_func_algod_localnet.restype = ctypes.c_void_p
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_free.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_pointer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_free_void.restype = None
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_void.restype = None
_UniffiLib.uniffi_algokit_utils_ffi_checksum_func_algod_localnet.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_func_algod_localnet.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_add_payment.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_add_payment.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_build.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_build.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_send.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_composer_send.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transactions.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transactions.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transaction.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsigner_sign_transaction.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsignergetter_get_signer.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_method_transactionsignergetter_get_signer.restype = ctypes.c_uint16
_UniffiLib.uniffi_algokit_utils_ffi_checksum_constructor_composer_new.argtypes = (
)
_UniffiLib.uniffi_algokit_utils_ffi_checksum_constructor_composer_new.restype = ctypes.c_uint16
_UniffiLib.ffi_algokit_utils_ffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_algokit_utils_ffi_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)



class AlgodClientProtocol(typing.Protocol):
    pass


class AlgodClient:
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_free_algodclient, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_algodclient, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst



class _UniffiConverterTypeAlgodClient:

    @staticmethod
    def lift(value: int):
        return AlgodClient._make_instance_(value)

    @staticmethod
    def check_lower(value: AlgodClient):
        if not isinstance(value, AlgodClient):
            raise TypeError("Expected AlgodClient instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: AlgodClientProtocol):
        if not isinstance(value, AlgodClient):
            raise TypeError("Expected AlgodClient instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: AlgodClientProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))



class ComposerProtocol(typing.Protocol):
    def add_payment(self, params: "PaymentParams"):
        raise NotImplementedError
    def build(self, ):
        raise NotImplementedError
    def send(self, ):
        raise NotImplementedError


class Composer:
    _pointer: ctypes.c_void_p
    def __init__(self, algod_client: "AlgodClient",signer_getter: "TransactionSignerGetter"):
        _UniffiConverterTypeAlgodClient.check_lower(algod_client)
        
        _UniffiConverterTypeTransactionSignerGetter.check_lower(signer_getter)
        
        self._pointer = _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_constructor_composer_new,
        _UniffiConverterTypeAlgodClient.lower(algod_client),
        _UniffiConverterTypeTransactionSignerGetter.lower(signer_getter))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_free_composer, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_composer, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def add_payment(self, params: "PaymentParams") -> None:
        _UniffiConverterTypePaymentParams.check_lower(params)
        
        _uniffi_rust_call_with_error(_UniffiConverterTypeUtilsError,_UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_add_payment,self._uniffi_clone_pointer(),
        _UniffiConverterTypePaymentParams.lower(params))





    async def build(self, ) -> None:

        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_build(
                self._uniffi_clone_pointer(), 
            ),
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_void,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_void,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_free_void,
            # lift function
            lambda val: None,
            
            
    # Error FFI converter
_UniffiConverterTypeUtilsError,

        )



    async def send(self, ) -> "typing.List[str]":
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_algokit_utils_ffi_fn_method_composer_send(
                self._uniffi_clone_pointer(), 
            ),
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_free_rust_buffer,
            # lift function
            _UniffiConverterSequenceString.lift,
            
    # Error FFI converter
_UniffiConverterTypeUtilsError,

        )





class _UniffiConverterTypeComposer:

    @staticmethod
    def lift(value: int):
        return Composer._make_instance_(value)

    @staticmethod
    def check_lower(value: Composer):
        if not isinstance(value, Composer):
            raise TypeError("Expected Composer instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: ComposerProtocol):
        if not isinstance(value, Composer):
            raise TypeError("Expected Composer instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: ComposerProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))



class TransactionSigner(typing.Protocol):
    def sign_transactions(self, transactions: "typing.List[Transaction]",indices: "typing.List[int]"):
        raise NotImplementedError
    def sign_transaction(self, transaction: "Transaction"):
        raise NotImplementedError


class TransactionSignerImpl:
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsigner, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsigner, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    async def sign_transactions(self, transactions: "typing.List[Transaction]",indices: "typing.List[int]") -> "typing.List[SignedTransaction]":
        _UniffiConverterSequenceTypeTransaction.check_lower(transactions)
        
        _UniffiConverterSequenceUInt32.check_lower(indices)
        
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transactions(
                self._uniffi_clone_pointer(), 
        _UniffiConverterSequenceTypeTransaction.lower(transactions),
        _UniffiConverterSequenceUInt32.lower(indices)
            ),
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_free_rust_buffer,
            # lift function
            _UniffiConverterSequenceTypeSignedTransaction.lift,
            
    # Error FFI converter
_UniffiConverterTypeUtilsError,

        )



    async def sign_transaction(self, transaction: "Transaction") -> "SignedTransaction":
        _UniffiConverterTypeTransaction.check_lower(transaction)
        
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsigner_sign_transaction(
                self._uniffi_clone_pointer(), 
        _UniffiConverterTypeTransaction.lower(transaction)
            ),
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_algokit_utils_ffi_rust_future_free_rust_buffer,
            # lift function
            _UniffiConverterTypeSignedTransaction.lift,
            
    # Error FFI converter
_UniffiConverterTypeUtilsError,

        )


# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
_UNIFFI_IDX_CALLBACK_FREE = 0
# Return codes for callback calls
_UNIFFI_CALLBACK_SUCCESS = 0
_UNIFFI_CALLBACK_ERROR = 1
_UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class _UniffiCallbackInterfaceFfiConverter:
    _handle_map = _UniffiHandleMap()

    @classmethod
    def lift(cls, handle):
        return cls._handle_map.get(handle)

    @classmethod
    def read(cls, buf):
        handle = buf.read_u64()
        cls.lift(handle)

    @classmethod
    def check_lower(cls, cb):
        pass

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.write_u64(cls.lower(cb))

# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplTransactionSigner:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD0
    def sign_transactions(
            uniffi_handle,
            transactions,
            indices,
            uniffi_future_callback,
            uniffi_callback_data,
            uniffi_out_return,
        ):
        uniffi_obj = _UniffiConverterTypeTransactionSigner._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterSequenceTypeTransaction.lift(transactions), _UniffiConverterSequenceUInt32.lift(indices), )
            method = uniffi_obj.sign_transactions
            return method(*args)

        
        def handle_success(return_value):
            uniffi_future_callback(
                uniffi_callback_data,
                _UniffiForeignFutureStructRustBuffer(
                    _UniffiConverterSequenceTypeSignedTransaction.lower(return_value),
                    _UniffiRustCallStatus.default()
                )
            )

        def handle_error(status_code, rust_buffer):
            uniffi_future_callback(
                uniffi_callback_data,
                _UniffiForeignFutureStructRustBuffer(
                    _UniffiRustBuffer.default(),
                    _UniffiRustCallStatus(status_code, rust_buffer),
                )
            )
        uniffi_out_return[0] = _uniffi_trait_interface_call_async_with_error(make_call, handle_success, handle_error, UtilsError, _UniffiConverterTypeUtilsError.lower)

    @_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_METHOD1
    def sign_transaction(
            uniffi_handle,
            transaction,
            uniffi_future_callback,
            uniffi_callback_data,
            uniffi_out_return,
        ):
        uniffi_obj = _UniffiConverterTypeTransactionSigner._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterTypeTransaction.lift(transaction), )
            method = uniffi_obj.sign_transaction
            return method(*args)

        
        def handle_success(return_value):
            uniffi_future_callback(
                uniffi_callback_data,
                _UniffiForeignFutureStructRustBuffer(
                    _UniffiConverterTypeSignedTransaction.lower(return_value),
                    _UniffiRustCallStatus.default()
                )
            )

        def handle_error(status_code, rust_buffer):
            uniffi_future_callback(
                uniffi_callback_data,
                _UniffiForeignFutureStructRustBuffer(
                    _UniffiRustBufferSignedTransaction.default(),
                    _UniffiRustCallStatus(status_code, rust_buffer),
                )
            )
        uniffi_out_return[0] = _uniffi_trait_interface_call_async_with_error(make_call, handle_success, handle_error, UtilsError, _UniffiConverterTypeUtilsError.lower)

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeTransactionSigner._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceTransactionSigner(
        sign_transactions,
        sign_transaction,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsigner(ctypes.byref(_uniffi_vtable))



class _UniffiConverterTypeTransactionSigner:
    _handle_map = _UniffiHandleMap()

    @staticmethod
    def lift(value: int):
        return TransactionSignerImpl._make_instance_(value)

    @staticmethod
    def check_lower(value: TransactionSigner):
        pass

    @staticmethod
    def lower(value: TransactionSigner):
        return _UniffiConverterTypeTransactionSigner._handle_map.insert(value)

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: TransactionSigner, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))



class TransactionSignerGetter(typing.Protocol):
    def get_signer(self, address: "str"):
        raise NotImplementedError


class TransactionSignerGetterImpl:
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_free_transactionsignergetter, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_clone_transactionsignergetter, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def get_signer(self, address: "str") -> "typing.Optional[TransactionSigner]":
        _UniffiConverterString.check_lower(address)
        
        return _UniffiConverterOptionalTypeTransactionSigner.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_method_transactionsignergetter_get_signer,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(address))
        )





# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplTransactionSignerGetter:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_TRANSACTION_SIGNER_GETTER_METHOD0
    def get_signer(
            uniffi_handle,
            address,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeTransactionSignerGetter._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(address), )
            method = uniffi_obj.get_signer
            return method(*args)

        
        def write_return_value(v):
            uniffi_out_return[0] = _UniffiConverterOptionalTypeTransactionSigner.lower(v)
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeTransactionSignerGetter._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceTransactionSignerGetter(
        get_signer,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_algokit_utils_ffi_fn_init_callback_vtable_transactionsignergetter(ctypes.byref(_uniffi_vtable))



class _UniffiConverterTypeTransactionSignerGetter:
    _handle_map = _UniffiHandleMap()

    @staticmethod
    def lift(value: int):
        return TransactionSignerGetterImpl._make_instance_(value)

    @staticmethod
    def check_lower(value: TransactionSignerGetter):
        pass

    @staticmethod
    def lower(value: TransactionSignerGetter):
        return _UniffiConverterTypeTransactionSignerGetter._handle_map.insert(value)

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: TransactionSignerGetter, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class CommonParams:
    sender: "str"
    signer: "typing.Optional[TransactionSigner]"
    rekey_to: "typing.Optional[str]"
    note: "typing.Optional[bytes]"
    lease: "typing.Optional[bytes]"
    static_fee: "typing.Optional[int]"
    extra_fee: "typing.Optional[int]"
    max_fee: "typing.Optional[int]"
    validity_window: "typing.Optional[int]"
    first_valid_round: "typing.Optional[int]"
    last_valid_round: "typing.Optional[int]"
    def __init__(self, *, sender: "str", signer: "typing.Optional[TransactionSigner]" = _DEFAULT, rekey_to: "typing.Optional[str]" = _DEFAULT, note: "typing.Optional[bytes]" = _DEFAULT, lease: "typing.Optional[bytes]" = _DEFAULT, static_fee: "typing.Optional[int]" = _DEFAULT, extra_fee: "typing.Optional[int]" = _DEFAULT, max_fee: "typing.Optional[int]" = _DEFAULT, validity_window: "typing.Optional[int]" = _DEFAULT, first_valid_round: "typing.Optional[int]" = _DEFAULT, last_valid_round: "typing.Optional[int]" = _DEFAULT):
        self.sender = sender
        if signer is _DEFAULT:
            self.signer = None
        else:
            self.signer = signer
        if rekey_to is _DEFAULT:
            self.rekey_to = None
        else:
            self.rekey_to = rekey_to
        if note is _DEFAULT:
            self.note = None
        else:
            self.note = note
        if lease is _DEFAULT:
            self.lease = None
        else:
            self.lease = lease
        if static_fee is _DEFAULT:
            self.static_fee = None
        else:
            self.static_fee = static_fee
        if extra_fee is _DEFAULT:
            self.extra_fee = None
        else:
            self.extra_fee = extra_fee
        if max_fee is _DEFAULT:
            self.max_fee = None
        else:
            self.max_fee = max_fee
        if validity_window is _DEFAULT:
            self.validity_window = None
        else:
            self.validity_window = validity_window
        if first_valid_round is _DEFAULT:
            self.first_valid_round = None
        else:
            self.first_valid_round = first_valid_round
        if last_valid_round is _DEFAULT:
            self.last_valid_round = None
        else:
            self.last_valid_round = last_valid_round

    def __str__(self):
        return "CommonParams(sender={}, signer={}, rekey_to={}, note={}, lease={}, static_fee={}, extra_fee={}, max_fee={}, validity_window={}, first_valid_round={}, last_valid_round={})".format(self.sender, self.signer, self.rekey_to, self.note, self.lease, self.static_fee, self.extra_fee, self.max_fee, self.validity_window, self.first_valid_round, self.last_valid_round)

    def __eq__(self, other):
        if self.sender != other.sender:
            return False
        if self.signer != other.signer:
            return False
        if self.rekey_to != other.rekey_to:
            return False
        if self.note != other.note:
            return False
        if self.lease != other.lease:
            return False
        if self.static_fee != other.static_fee:
            return False
        if self.extra_fee != other.extra_fee:
            return False
        if self.max_fee != other.max_fee:
            return False
        if self.validity_window != other.validity_window:
            return False
        if self.first_valid_round != other.first_valid_round:
            return False
        if self.last_valid_round != other.last_valid_round:
            return False
        return True

class _UniffiConverterTypeCommonParams(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return CommonParams(
            sender=_UniffiConverterString.read(buf),
            signer=_UniffiConverterOptionalTypeTransactionSigner.read(buf),
            rekey_to=_UniffiConverterOptionalString.read(buf),
            note=_UniffiConverterOptionalBytes.read(buf),
            lease=_UniffiConverterOptionalBytes.read(buf),
            static_fee=_UniffiConverterOptionalUInt64.read(buf),
            extra_fee=_UniffiConverterOptionalUInt64.read(buf),
            max_fee=_UniffiConverterOptionalUInt64.read(buf),
            validity_window=_UniffiConverterOptionalUInt64.read(buf),
            first_valid_round=_UniffiConverterOptionalUInt64.read(buf),
            last_valid_round=_UniffiConverterOptionalUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.sender)
        _UniffiConverterOptionalTypeTransactionSigner.check_lower(value.signer)
        _UniffiConverterOptionalString.check_lower(value.rekey_to)
        _UniffiConverterOptionalBytes.check_lower(value.note)
        _UniffiConverterOptionalBytes.check_lower(value.lease)
        _UniffiConverterOptionalUInt64.check_lower(value.static_fee)
        _UniffiConverterOptionalUInt64.check_lower(value.extra_fee)
        _UniffiConverterOptionalUInt64.check_lower(value.max_fee)
        _UniffiConverterOptionalUInt64.check_lower(value.validity_window)
        _UniffiConverterOptionalUInt64.check_lower(value.first_valid_round)
        _UniffiConverterOptionalUInt64.check_lower(value.last_valid_round)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.sender, buf)
        _UniffiConverterOptionalTypeTransactionSigner.write(value.signer, buf)
        _UniffiConverterOptionalString.write(value.rekey_to, buf)
        _UniffiConverterOptionalBytes.write(value.note, buf)
        _UniffiConverterOptionalBytes.write(value.lease, buf)
        _UniffiConverterOptionalUInt64.write(value.static_fee, buf)
        _UniffiConverterOptionalUInt64.write(value.extra_fee, buf)
        _UniffiConverterOptionalUInt64.write(value.max_fee, buf)
        _UniffiConverterOptionalUInt64.write(value.validity_window, buf)
        _UniffiConverterOptionalUInt64.write(value.first_valid_round, buf)
        _UniffiConverterOptionalUInt64.write(value.last_valid_round, buf)


class PaymentParams:
    common_params: "CommonParams"
    """
    Common transaction parameters.
    """

    receiver: "str"
    """
    The address of the account receiving the ALGO payment.
    """

    amount: "int"
    """
    The amount of microALGO to send.

    Specified in microALGO (1 ALGO = 1,000,000 microALGO).
    """

    def __init__(self, *, common_params: "CommonParams", receiver: "str", amount: "int"):
        self.common_params = common_params
        self.receiver = receiver
        self.amount = amount

    def __str__(self):
        return "PaymentParams(common_params={}, receiver={}, amount={})".format(self.common_params, self.receiver, self.amount)

    def __eq__(self, other):
        if self.common_params != other.common_params:
            return False
        if self.receiver != other.receiver:
            return False
        if self.amount != other.amount:
            return False
        return True

class _UniffiConverterTypePaymentParams(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return PaymentParams(
            common_params=_UniffiConverterTypeCommonParams.read(buf),
            receiver=_UniffiConverterString.read(buf),
            amount=_UniffiConverterUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypeCommonParams.check_lower(value.common_params)
        _UniffiConverterString.check_lower(value.receiver)
        _UniffiConverterUInt64.check_lower(value.amount)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypeCommonParams.write(value.common_params, buf)
        _UniffiConverterString.write(value.receiver, buf)
        _UniffiConverterUInt64.write(value.amount, buf)


# UtilsError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class UtilsError(Exception):
    pass

_UniffiTempUtilsError = UtilsError

class UtilsError:  # type: ignore
    class UtilsError(_UniffiTempUtilsError):
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "UtilsError.UtilsError({})".format(str(self))
    _UniffiTempUtilsError.UtilsError = UtilsError # type: ignore

UtilsError = _UniffiTempUtilsError # type: ignore
del _UniffiTempUtilsError


class _UniffiConverterTypeUtilsError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return UtilsError.UtilsError(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, UtilsError.UtilsError):
            _UniffiConverterString.check_lower(value.message)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, UtilsError.UtilsError):
            buf.write_i32(1)
            _UniffiConverterString.write(value.message, buf)



class _UniffiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalBytes(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterBytes.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterBytes.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterBytes.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeTransactionSigner(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeTransactionSigner.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeTransactionSigner.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeTransactionSigner.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceUInt32(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterUInt32.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterUInt32.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterUInt32.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterString.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeSignedTransaction(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeSignedTransaction.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeSignedTransaction.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeSignedTransaction.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeTransaction(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeTransaction.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeTransaction.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeTransaction.read(buf) for i in range(count)
        ]

# External type SignedTransaction is in namespace "algokit_transact_ffi", crate algokit_transact_ffi




# External type Transaction is in namespace "algokit_transact_ffi", crate algokit_transact_ffi




# Async support# RustFuturePoll values
_UNIFFI_RUST_FUTURE_POLL_READY = 0
_UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1

# Stores futures for _uniffi_continuation_callback
_UniffiContinuationHandleMap = _UniffiHandleMap()

_UNIFFI_GLOBAL_EVENT_LOOP = None

"""
Set the event loop to use for async functions

This is needed if some async functions run outside of the eventloop, for example:
    - A non-eventloop thread is spawned, maybe from `EventLoop.run_in_executor` or maybe from the
      Rust code spawning its own thread.
    - The Rust code calls an async callback method from a sync callback function, using something
      like `pollster` to block on the async call.

In this case, we need an event loop to run the Python async function, but there's no eventloop set
for the thread.  Use `uniffi_set_event_loop` to force an eventloop to be used in this case.
"""
def uniffi_set_event_loop(eventloop: asyncio.BaseEventLoop):
    global _UNIFFI_GLOBAL_EVENT_LOOP
    _UNIFFI_GLOBAL_EVENT_LOOP = eventloop

def _uniffi_get_event_loop():
    if _UNIFFI_GLOBAL_EVENT_LOOP is not None:
        return _UNIFFI_GLOBAL_EVENT_LOOP
    else:
        return asyncio.get_running_loop()

# Continuation callback for async functions
# lift the return value or error and resolve the future, causing the async function to resume.
@_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK
def _uniffi_continuation_callback(future_ptr, poll_code):
    (eventloop, future) = _UniffiContinuationHandleMap.remove(future_ptr)
    eventloop.call_soon_threadsafe(_uniffi_set_future_result, future, poll_code)

def _uniffi_set_future_result(future, poll_code):
    if not future.cancelled():
        future.set_result(poll_code)

async def _uniffi_rust_call_async(rust_future, ffi_poll, ffi_complete, ffi_free, lift_func, error_ffi_converter):
    try:
        eventloop = _uniffi_get_event_loop()

        # Loop and poll until we see a _UNIFFI_RUST_FUTURE_POLL_READY value
        while True:
            future = eventloop.create_future()
            ffi_poll(
                rust_future,
                _uniffi_continuation_callback,
                _UniffiContinuationHandleMap.insert((eventloop, future)),
            )
            poll_code = await future
            if poll_code == _UNIFFI_RUST_FUTURE_POLL_READY:
                break

        return lift_func(
            _uniffi_rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
        )
    finally:
        ffi_free(rust_future)
def _uniffi_trait_interface_call_async(make_call, handle_success, handle_error):
    async def make_call_and_call_callback():
        try:
            handle_success(await make_call())
        except Exception as e:
            print("UniFFI: Unhandled exception in trait interface call", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
            handle_error(
                _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR,
                _UniffiConverterString.lower(repr(e)),
            )
    eventloop = _uniffi_get_event_loop()
    task = asyncio.run_coroutine_threadsafe(make_call_and_call_callback(), eventloop)
    handle = _UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert((eventloop, task))
    return _UniffiForeignFuture(handle, _uniffi_foreign_future_free)

def _uniffi_trait_interface_call_async_with_error(make_call, handle_success, handle_error, error_type, lower_error):
    async def make_call_and_call_callback():
        try:
            try:
                handle_success(await make_call())
            except error_type as e:
                handle_error(
                    _UniffiRustCallStatus.CALL_ERROR,
                    lower_error(e),
                )
        except Exception as e:
            print("UniFFI: Unhandled exception in trait interface call", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
            handle_error(
                _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR,
                _UniffiConverterString.lower(repr(e)),
            )
    eventloop = _uniffi_get_event_loop()
    task = asyncio.run_coroutine_threadsafe(make_call_and_call_callback(), eventloop)
    handle = _UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert((eventloop, task))
    return _UniffiForeignFuture(handle, _uniffi_foreign_future_free)

_UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = _UniffiHandleMap()

@_UNIFFI_FOREIGN_FUTURE_FREE
def _uniffi_foreign_future_free(handle):
    (eventloop, task) = _UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle)
    eventloop.call_soon(_uniffi_foreign_future_do_free, task)

def _uniffi_foreign_future_do_free(task):
    if not task.done():
        task.cancel()

def algod_localnet() -> "AlgodClient":
    return _UniffiConverterTypeAlgodClient.lift(_uniffi_rust_call(_UniffiLib.uniffi_algokit_utils_ffi_fn_func_algod_localnet,))


__all__ = [
    "InternalError",
    "UtilsError",
    "CommonParams",
    "PaymentParams",
    "algod_localnet",
    "AlgodClient",
    "Composer",
    "TransactionSigner",
    "TransactionSignerGetter",
]

