// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.algokit_composer_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Callback
import com.sun.jna.IntegerType
import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
  // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
  // When dealing with these fields, make sure to call `toULong()`.
  @JvmField var capacity: Long = 0

  @JvmField var len: Long = 0

  @JvmField var data: Pointer? = null

  class ByValue :
    RustBuffer(),
    Structure.ByValue

  class ByReference :
    RustBuffer(),
    Structure.ByReference

  internal fun setValue(other: RustBuffer) {
    capacity = other.capacity
    len = other.len
    data = other.data
  }

  companion object {
    internal fun alloc(size: ULong = 0UL) =
      uniffiRustCall { status ->
        // Note: need to convert the size to a `Long` value to make this work with JVM.
        UniffiLib.INSTANCE.ffi_algokit_composer_ffi_rustbuffer_alloc(size.toLong(), status)
      }.also {
        if (it.data == null) {
          throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=$size)")
        }
      }

    internal fun create(
      capacity: ULong,
      len: ULong,
      data: Pointer?,
    ): RustBuffer.ByValue {
      var buf = RustBuffer.ByValue()
      buf.capacity = capacity.toLong()
      buf.len = len.toLong()
      buf.data = data
      return buf
    }

    internal fun free(buf: RustBuffer.ByValue) =
      uniffiRustCall { status ->
        UniffiLib.INSTANCE.ffi_algokit_composer_ffi_rustbuffer_free(buf, status)
      }
  }

  @Suppress("TooGenericExceptionThrown")
  fun asByteBuffer() =
    this.data?.getByteBuffer(0, this.len.toLong())?.also {
      it.order(ByteOrder.BIG_ENDIAN)
    }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
  /**
   * Set the pointed-to `RustBuffer` to the given value.
   */
  fun setValue(value: RustBuffer.ByValue) {
    // NOTE: The offsets are as they are in the C-like struct.
    val pointer = getPointer()
    pointer.setLong(0, value.capacity)
    pointer.setLong(8, value.len)
    pointer.setPointer(16, value.data)
  }

  /**
   * Get a `RustBuffer.ByValue` from this reference.
   */
  fun getValue(): RustBuffer.ByValue {
    val pointer = getPointer()
    val value = RustBuffer.ByValue()
    value.writeField("capacity", pointer.getLong(0))
    value.writeField("len", pointer.getLong(8))
    value.writeField("data", pointer.getLong(16))

    return value
  }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
  @JvmField var len: Int = 0

  @JvmField var data: Pointer? = null

  class ByValue :
    ForeignBytes(),
    Structure.ByValue
}

/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
  // Convert an FFI type to a Kotlin type
  fun lift(value: FfiType): KotlinType

  // Convert an Kotlin type to an FFI type
  fun lower(value: KotlinType): FfiType

  // Read a Kotlin type from a `ByteBuffer`
  fun read(buf: ByteBuffer): KotlinType

  // Calculate bytes to allocate when creating a `RustBuffer`
  //
  // This must return at least as many bytes as the write() function will
  // write. It can return more bytes than needed, for example when writing
  // Strings we can't know the exact bytes needed until we the UTF-8
  // encoding, so we pessimistically allocate the largest size possible (3
  // bytes per codepoint).  Allocating extra bytes is not really a big deal
  // because the `RustBuffer` is short-lived.
  fun allocationSize(value: KotlinType): ULong

  // Write a Kotlin type to a `ByteBuffer`
  fun write(
    value: KotlinType,
    buf: ByteBuffer,
  )

  // Lower a value into a `RustBuffer`
  //
  // This method lowers a value into a `RustBuffer` rather than the normal
  // FfiType.  It's used by the callback interface code.  Callback interface
  // returns are always serialized into a `RustBuffer` regardless of their
  // normal FFI type.
  fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
    val rbuf = RustBuffer.alloc(allocationSize(value))
    try {
      val bbuf =
        rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
          it.order(ByteOrder.BIG_ENDIAN)
        }
      write(value, bbuf)
      rbuf.writeField("len", bbuf.position().toLong())
      return rbuf
    } catch (e: Throwable) {
      RustBuffer.free(rbuf)
      throw e
    }
  }

  // Lift a value from a `RustBuffer`.
  //
  // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
  // It's currently only used by the `FfiConverterRustBuffer` class below.
  fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
    val byteBuf = rbuf.asByteBuffer()!!
    try {
      val item = read(byteBuf)
      if (byteBuf.hasRemaining()) {
        throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
      }
      return item
    } finally {
      RustBuffer.free(rbuf)
    }
  }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType> : FfiConverter<KotlinType, RustBuffer.ByValue> {
  override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)

  override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
  @JvmField var code: Byte = 0

  @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

  class ByValue :
    UniffiRustCallStatus(),
    Structure.ByValue

  fun isSuccess(): Boolean = code == UNIFFI_CALL_SUCCESS

  fun isError(): Boolean = code == UNIFFI_CALL_ERROR

  fun isPanic(): Boolean = code == UNIFFI_CALL_UNEXPECTED_ERROR

  companion object {
    fun create(
      code: Byte,
      errorBuf: RustBuffer.ByValue,
    ): UniffiRustCallStatus.ByValue {
      val callStatus = UniffiRustCallStatus.ByValue()
      callStatus.code = code
      callStatus.error_buf = errorBuf
      return callStatus
    }
  }
}

class InternalException(
  message: String,
) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
  fun lift(error_buf: RustBuffer.ByValue): E
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E : kotlin.Exception> uniffiRustCallWithError(
  errorHandler: UniffiRustCallStatusErrorHandler<E>,
  callback: (UniffiRustCallStatus) -> U,
): U {
  var status = UniffiRustCallStatus()
  val return_value = callback(status)
  uniffiCheckCallStatus(errorHandler, status)
  return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun <E : kotlin.Exception> uniffiCheckCallStatus(
  errorHandler: UniffiRustCallStatusErrorHandler<E>,
  status: UniffiRustCallStatus,
) {
  if (status.isSuccess()) {
    return
  } else if (status.isError()) {
    throw errorHandler.lift(status.error_buf)
  } else if (status.isPanic()) {
    // when the rust code sees a panic, it tries to construct a rustbuffer
    // with the message.  but if that code panics, then it just sends back
    // an empty buffer.
    if (status.error_buf.len > 0) {
      throw InternalException(FfiConverterString.lift(status.error_buf))
    } else {
      throw InternalException("Rust panic")
    }
  } else {
    throw InternalException("Unknown rust call status: $status.code")
  }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler : UniffiRustCallStatusErrorHandler<InternalException> {
  override fun lift(error_buf: RustBuffer.ByValue): InternalException {
    RustBuffer.free(error_buf)
    return InternalException("Unexpected CALL_ERROR")
  }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U =
  uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)

internal inline fun <T> uniffiTraitInterfaceCall(
  callStatus: UniffiRustCallStatus,
  makeCall: () -> T,
  writeReturn: (T) -> Unit,
) {
  try {
    writeReturn(makeCall())
  } catch (e: kotlin.Exception) {
    callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
    callStatus.error_buf = FfiConverterString.lower(e.toString())
  }
}

internal inline fun <T, reified E : Throwable> uniffiTraitInterfaceCallWithError(
  callStatus: UniffiRustCallStatus,
  makeCall: () -> T,
  writeReturn: (T) -> Unit,
  lowerError: (E) -> RustBuffer.ByValue,
) {
  try {
    writeReturn(makeCall())
  } catch (e: kotlin.Exception) {
    if (e is E) {
      callStatus.code = UNIFFI_CALL_ERROR
      callStatus.error_buf = lowerError(e)
    } else {
      callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
      callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
  }
}

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T : Any> {
  private val map = ConcurrentHashMap<Long, T>()
  private val counter =
    java.util.concurrent.atomic
      .AtomicLong(0)

  val size: Int
    get() = map.size

  // Insert a new object into the handle map and get a handle for it
  fun insert(obj: T): Long {
    val handle = counter.getAndAdd(1)
    map.put(handle, obj)
    return handle
  }

  // Get an object from the handle map
  fun get(handle: Long): T = map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")

  // Remove an entry from the handlemap and get the Kotlin object back
  fun remove(handle: Long): T = map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
  val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
  if (libOverride != null) {
    return libOverride
  }
  return "algokit_composer_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(componentName: String): Lib =
  Native.load<Lib>(findLibraryName(componentName), Lib::class.java)

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
  fun callback(
    `data`: Long,
    `pollResult`: Byte,
  )
}

internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
  fun callback(`handle`: Long)
}

internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
  fun callback(`handle`: Long)
}

@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
  @JvmField internal var `handle`: Long = 0.toLong(),
  @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
  class UniffiByValue(
    `handle`: Long = 0.toLong(),
    `free`: UniffiForeignFutureFree? = null,
  ) : UniffiForeignFuture(`handle`, `free`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFuture) {
    `handle` = other.`handle`
    `free` = other.`free`
  }
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
  @JvmField internal var `returnValue`: Byte = 0.toByte(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Byte = 0.toByte(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructU8(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructU8.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
  @JvmField internal var `returnValue`: Byte = 0.toByte(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Byte = 0.toByte(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructI8(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructI8.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
  @JvmField internal var `returnValue`: Short = 0.toShort(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Short = 0.toShort(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructU16(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructU16.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
  @JvmField internal var `returnValue`: Short = 0.toShort(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Short = 0.toShort(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructI16(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructI16.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
  @JvmField internal var `returnValue`: Int = 0,
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Int = 0,
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructU32(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructU32.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
  @JvmField internal var `returnValue`: Int = 0,
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Int = 0,
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructI32(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructI32.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
  @JvmField internal var `returnValue`: Long = 0.toLong(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Long = 0.toLong(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructU64(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructU64.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
  @JvmField internal var `returnValue`: Long = 0.toLong(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Long = 0.toLong(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructI64(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructI64.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
  @JvmField internal var `returnValue`: Float = 0.0f,
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Float = 0.0f,
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructF32(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructF32.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
  @JvmField internal var `returnValue`: Double = 0.0,
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Double = 0.0,
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructF64(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructF64.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
  @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: Pointer = Pointer.NULL,
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructPointer(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructPointer.UniffiByValue,
  )
}

@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
  @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructRustBuffer(`returnValue`, `callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
    `returnValue` = other.`returnValue`
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,
  )
}

@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
  @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
  class UniffiByValue(
    `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
  ) : UniffiForeignFutureStructVoid(`callStatus`),
    Structure.ByValue

  internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
    `callStatus` = other.`callStatus`
  }
}

internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
  fun callback(
    `callbackData`: Long,
    `result`: UniffiForeignFutureStructVoid.UniffiByValue,
  )
}

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
//
// The `ffi_uniffi_contract_version` method and all checksum methods are put
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
  // Integrity check functions only
  fun uniffi_algokit_composer_ffi_checksum_func_build_signed_simulate_request(): Short

  fun uniffi_algokit_composer_ffi_checksum_func_build_unsigned_simulate_request(): Short

  fun uniffi_algokit_composer_ffi_checksum_func_compose(): Short

  fun uniffi_algokit_composer_ffi_checksum_func_map_simulate_response(): Short

  fun uniffi_algokit_composer_ffi_checksum_func_sign_transactions(): Short

  fun ffi_algokit_composer_ffi_uniffi_contract_version(): Int
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
  companion object {
    internal val INSTANCE: UniffiLib by lazy {
      val componentName = "algokit_composer_ffi"
      // For large crates we prevent `MethodTooLargeException` (see #2340)
      // N.B. the name of the extension is very misleading, since it is
      // rather `InterfaceTooLargeException`, caused by too many methods
      // in the interface for large crates.
      //
      // By splitting the otherwise huge interface into two parts
      // * UniffiLib (this)
      // * IntegrityCheckingUniffiLib
      // And all checksum methods are put into `IntegrityCheckingUniffiLib`
      // we allow for ~2x as many methods in the UniffiLib interface.
      //
      // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
      // so that we can (optionally!) call `uniffiCheckApiChecksums`...
      loadIndirect<IntegrityCheckingUniffiLib>(componentName)
        .also { lib: IntegrityCheckingUniffiLib ->
          uniffiCheckContractApiVersion(lib)
          uniffiCheckApiChecksums(lib)
        }
      // ... and then we load the library as `UniffiLib`
      // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
      // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
      // error. So we must call `loadIndirect` twice. For crates large enough
      // to trigger this issue, the performance impact is negligible, running on
      // a macOS M1 machine the `loadIndirect` call takes ~50ms.
      val lib = loadIndirect<UniffiLib>(componentName)
      // No need to check the contract version and checksums, since
      // we already did that with `IntegrityCheckingUniffiLib` above.
      // Loading of library with integrity check done.
      lib
    }
  }

  // FFI functions
  fun uniffi_algokit_composer_ffi_fn_func_build_signed_simulate_request(
    `signedTransactions`: RustBuffer.ByValue,
    `options`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun uniffi_algokit_composer_ffi_fn_func_build_unsigned_simulate_request(
    `transactions`: RustBuffer.ByValue,
    `options`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun uniffi_algokit_composer_ffi_fn_func_compose(
    `txnParams`: RustBuffer.ByValue,
    `composerParams`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun uniffi_algokit_composer_ffi_fn_func_map_simulate_response(
    `transactions`: RustBuffer.ByValue,
    `response`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun uniffi_algokit_composer_ffi_fn_func_sign_transactions(
    `transactionBytes`: RustBuffer.ByValue,
    `secretKeys`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun ffi_algokit_composer_ffi_rustbuffer_alloc(
    `size`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun ffi_algokit_composer_ffi_rustbuffer_from_bytes(
    `bytes`: ForeignBytes.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun ffi_algokit_composer_ffi_rustbuffer_free(
    `buf`: RustBuffer.ByValue,
    uniffi_out_err: UniffiRustCallStatus,
  ): Unit

  fun ffi_algokit_composer_ffi_rustbuffer_reserve(
    `buf`: RustBuffer.ByValue,
    `additional`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun ffi_algokit_composer_ffi_rust_future_poll_u8(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_u8(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_u8(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_u8(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Byte

  fun ffi_algokit_composer_ffi_rust_future_poll_i8(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_i8(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_i8(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_i8(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Byte

  fun ffi_algokit_composer_ffi_rust_future_poll_u16(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_u16(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_u16(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_u16(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Short

  fun ffi_algokit_composer_ffi_rust_future_poll_i16(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_i16(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_i16(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_i16(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Short

  fun ffi_algokit_composer_ffi_rust_future_poll_u32(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_u32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_u32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_u32(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Int

  fun ffi_algokit_composer_ffi_rust_future_poll_i32(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_i32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_i32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_i32(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Int

  fun ffi_algokit_composer_ffi_rust_future_poll_u64(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_u64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_u64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_u64(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Long

  fun ffi_algokit_composer_ffi_rust_future_poll_i64(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_i64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_i64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_i64(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Long

  fun ffi_algokit_composer_ffi_rust_future_poll_f32(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_f32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_f32(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_f32(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Float

  fun ffi_algokit_composer_ffi_rust_future_poll_f64(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_f64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_f64(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_f64(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Double

  fun ffi_algokit_composer_ffi_rust_future_poll_pointer(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_pointer(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_pointer(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_pointer(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Pointer

  fun ffi_algokit_composer_ffi_rust_future_poll_rust_buffer(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_rust_buffer(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_rust_buffer(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_rust_buffer(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): RustBuffer.ByValue

  fun ffi_algokit_composer_ffi_rust_future_poll_void(
    `handle`: Long,
    `callback`: UniffiRustFutureContinuationCallback,
    `callbackData`: Long,
  ): Unit

  fun ffi_algokit_composer_ffi_rust_future_cancel_void(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_free_void(`handle`: Long): Unit

  fun ffi_algokit_composer_ffi_rust_future_complete_void(
    `handle`: Long,
    uniffi_out_err: UniffiRustCallStatus,
  ): Unit
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
  // Get the bindings contract version from our ComponentInterface
  val bindings_contract_version = 29
  // Get the scaffolding contract version by calling the into the dylib
  val scaffolding_contract_version = lib.ffi_algokit_composer_ffi_uniffi_contract_version()
  if (bindings_contract_version != scaffolding_contract_version) {
    throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
  }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
  if (lib.uniffi_algokit_composer_ffi_checksum_func_build_signed_simulate_request() != 31440.toShort()) {
    throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
  if (lib.uniffi_algokit_composer_ffi_checksum_func_build_unsigned_simulate_request() != 27549.toShort()) {
    throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
  if (lib.uniffi_algokit_composer_ffi_checksum_func_compose() != 7997.toShort()) {
    throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
  if (lib.uniffi_algokit_composer_ffi_checksum_func_map_simulate_response() != 41676.toShort()) {
    throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
  if (lib.uniffi_algokit_composer_ffi_checksum_func_sign_transactions() != 48318.toShort()) {
    throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
  UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.

// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
  fun destroy()

  companion object {
    fun destroy(vararg args: Any?) {
      for (arg in args) {
        when (arg) {
          is Disposable -> {
            arg.destroy()
          }

          is ArrayList<*> -> {
            for (idx in arg.indices) {
              val element = arg[idx]
              if (element is Disposable) {
                element.destroy()
              }
            }
          }

          is Map<*, *> -> {
            for (element in arg.values) {
              if (element is Disposable) {
                element.destroy()
              }
            }
          }

          is Iterable<*> -> {
            for (element in arg) {
              if (element is Disposable) {
                element.destroy()
              }
            }
          }
        }
      }
    }
  }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
  try {
    block(this)
  } finally {
    try {
      // N.B. our implementation is on the nullable type `Disposable?`.
      this?.destroy()
    } catch (e: Throwable) {
      // swallow
    }
  }

/**
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt : FfiConverter<UInt, Int> {
  override fun lift(value: Int): UInt = value.toUInt()

  override fun read(buf: ByteBuffer): UInt = lift(buf.getInt())

  override fun lower(value: UInt): Int = value.toInt()

  override fun allocationSize(value: UInt) = 4UL

  override fun write(
    value: UInt,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.toInt())
  }
}

/**
 * @suppress
 */
public object FfiConverterULong : FfiConverter<ULong, Long> {
  override fun lift(value: Long): ULong = value.toULong()

  override fun read(buf: ByteBuffer): ULong = lift(buf.getLong())

  override fun lower(value: ULong): Long = value.toLong()

  override fun allocationSize(value: ULong) = 8UL

  override fun write(
    value: ULong,
    buf: ByteBuffer,
  ) {
    buf.putLong(value.toLong())
  }
}

/**
 * @suppress
 */
public object FfiConverterBoolean : FfiConverter<Boolean, Byte> {
  override fun lift(value: Byte): Boolean = value.toInt() != 0

  override fun read(buf: ByteBuffer): Boolean = lift(buf.get())

  override fun lower(value: Boolean): Byte = if (value) 1.toByte() else 0.toByte()

  override fun allocationSize(value: Boolean) = 1UL

  override fun write(
    value: Boolean,
    buf: ByteBuffer,
  ) {
    buf.put(lower(value))
  }
}

/**
 * @suppress
 */
public object FfiConverterString : FfiConverter<String, RustBuffer.ByValue> {
  // Note: we don't inherit from FfiConverterRustBuffer, because we use a
  // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
  // store our length and avoid writing it out to the buffer.
  override fun lift(value: RustBuffer.ByValue): String {
    try {
      val byteArr = ByteArray(value.len.toInt())
      value.asByteBuffer()!!.get(byteArr)
      return byteArr.toString(Charsets.UTF_8)
    } finally {
      RustBuffer.free(value)
    }
  }

  override fun read(buf: ByteBuffer): String {
    val len = buf.getInt()
    val byteArr = ByteArray(len)
    buf.get(byteArr)
    return byteArr.toString(Charsets.UTF_8)
  }

  fun toUtf8(value: String): ByteBuffer {
    // Make sure we don't have invalid UTF-16, check for lone surrogates.
    return Charsets.UTF_8.newEncoder().run {
      onMalformedInput(CodingErrorAction.REPORT)
      encode(CharBuffer.wrap(value))
    }
  }

  override fun lower(value: String): RustBuffer.ByValue {
    val byteBuf = toUtf8(value)
    // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
    // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
    val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
    rbuf.asByteBuffer()!!.put(byteBuf)
    return rbuf
  }

  // We aren't sure exactly how many bytes our string will be once it's UTF-8
  // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
  // enough.
  override fun allocationSize(value: String): ULong {
    val sizeForLength = 4UL
    val sizeForString = value.length.toULong() * 3UL
    return sizeForLength + sizeForString
  }

  override fun write(
    value: String,
    buf: ByteBuffer,
  ) {
    val byteBuf = toUtf8(value)
    buf.putInt(byteBuf.limit())
    buf.put(byteBuf)
  }
}

/**
 * @suppress
 */
public object FfiConverterByteArray : FfiConverterRustBuffer<ByteArray> {
  override fun read(buf: ByteBuffer): ByteArray {
    val len = buf.getInt()
    val byteArr = ByteArray(len)
    buf.get(byteArr)
    return byteArr
  }

  override fun allocationSize(value: ByteArray): ULong = 4UL + value.size.toULong()

  override fun write(
    value: ByteArray,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    buf.put(value)
  }
}

data class AssetOptInParams(
  var `common`: CommonTxnParams,
  var `assetId`: kotlin.ULong,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAssetOptInParams : FfiConverterRustBuffer<AssetOptInParams> {
  override fun read(buf: ByteBuffer): AssetOptInParams =
    AssetOptInParams(
      FfiConverterTypeCommonTxnParams.read(buf),
      FfiConverterULong.read(buf),
    )

  override fun allocationSize(value: AssetOptInParams) =
    (
      FfiConverterTypeCommonTxnParams.allocationSize(value.`common`) +
        FfiConverterULong.allocationSize(value.`assetId`)
    )

  override fun write(
    value: AssetOptInParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeCommonTxnParams.write(value.`common`, buf)
    FfiConverterULong.write(value.`assetId`, buf)
  }
}

data class AssetTransferParams(
  var `common`: CommonTxnParams,
  var `assetId`: kotlin.ULong,
  var `receiver`: kotlin.String,
  var `amount`: kotlin.ULong,
  var `clawbackTarget`: kotlin.String? = null,
  var `closeAssetTo`: kotlin.String? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAssetTransferParams : FfiConverterRustBuffer<AssetTransferParams> {
  override fun read(buf: ByteBuffer): AssetTransferParams =
    AssetTransferParams(
      FfiConverterTypeCommonTxnParams.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterString.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterOptionalString.read(buf),
      FfiConverterOptionalString.read(buf),
    )

  override fun allocationSize(value: AssetTransferParams) =
    (
      FfiConverterTypeCommonTxnParams.allocationSize(value.`common`) +
        FfiConverterULong.allocationSize(value.`assetId`) +
        FfiConverterString.allocationSize(value.`receiver`) +
        FfiConverterULong.allocationSize(value.`amount`) +
        FfiConverterOptionalString.allocationSize(value.`clawbackTarget`) +
        FfiConverterOptionalString.allocationSize(value.`closeAssetTo`)
    )

  override fun write(
    value: AssetTransferParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeCommonTxnParams.write(value.`common`, buf)
    FfiConverterULong.write(value.`assetId`, buf)
    FfiConverterString.write(value.`receiver`, buf)
    FfiConverterULong.write(value.`amount`, buf)
    FfiConverterOptionalString.write(value.`clawbackTarget`, buf)
    FfiConverterOptionalString.write(value.`closeAssetTo`, buf)
  }
}

data class CommonTxnParams(
  var `sender`: kotlin.String,
  var `note`: kotlin.ByteArray? = null,
  var `lease`: kotlin.ByteArray? = null,
  var `rekeyTo`: kotlin.String? = null,
  var `staticFee`: kotlin.ULong? = null,
  var `extraFee`: kotlin.ULong? = null,
  var `maxFee`: kotlin.ULong? = null,
  var `validityWindow`: kotlin.ULong? = null,
  var `firstValidRound`: kotlin.ULong? = null,
  var `lastValidRound`: kotlin.ULong? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCommonTxnParams : FfiConverterRustBuffer<CommonTxnParams> {
  override fun read(buf: ByteBuffer): CommonTxnParams =
    CommonTxnParams(
      FfiConverterString.read(buf),
      FfiConverterOptionalByteArray.read(buf),
      FfiConverterOptionalByteArray.read(buf),
      FfiConverterOptionalString.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
    )

  override fun allocationSize(value: CommonTxnParams) =
    (
      FfiConverterString.allocationSize(value.`sender`) +
        FfiConverterOptionalByteArray.allocationSize(value.`note`) +
        FfiConverterOptionalByteArray.allocationSize(value.`lease`) +
        FfiConverterOptionalString.allocationSize(value.`rekeyTo`) +
        FfiConverterOptionalULong.allocationSize(value.`staticFee`) +
        FfiConverterOptionalULong.allocationSize(value.`extraFee`) +
        FfiConverterOptionalULong.allocationSize(value.`maxFee`) +
        FfiConverterOptionalULong.allocationSize(value.`validityWindow`) +
        FfiConverterOptionalULong.allocationSize(value.`firstValidRound`) +
        FfiConverterOptionalULong.allocationSize(value.`lastValidRound`)
    )

  override fun write(
    value: CommonTxnParams,
    buf: ByteBuffer,
  ) {
    FfiConverterString.write(value.`sender`, buf)
    FfiConverterOptionalByteArray.write(value.`note`, buf)
    FfiConverterOptionalByteArray.write(value.`lease`, buf)
    FfiConverterOptionalString.write(value.`rekeyTo`, buf)
    FfiConverterOptionalULong.write(value.`staticFee`, buf)
    FfiConverterOptionalULong.write(value.`extraFee`, buf)
    FfiConverterOptionalULong.write(value.`maxFee`, buf)
    FfiConverterOptionalULong.write(value.`validityWindow`, buf)
    FfiConverterOptionalULong.write(value.`firstValidRound`, buf)
    FfiConverterOptionalULong.write(value.`lastValidRound`, buf)
  }
}

data class ComposerParams(
  var `suggestedParams`: SuggestedParams,
  var `defaultValidityWindow`: kotlin.ULong? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeComposerParams : FfiConverterRustBuffer<ComposerParams> {
  override fun read(buf: ByteBuffer): ComposerParams =
    ComposerParams(
      FfiConverterTypeSuggestedParams.read(buf),
      FfiConverterOptionalULong.read(buf),
    )

  override fun allocationSize(value: ComposerParams) =
    (
      FfiConverterTypeSuggestedParams.allocationSize(value.`suggestedParams`) +
        FfiConverterOptionalULong.allocationSize(value.`defaultValidityWindow`)
    )

  override fun write(
    value: ComposerParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeSuggestedParams.write(value.`suggestedParams`, buf)
    FfiConverterOptionalULong.write(value.`defaultValidityWindow`, buf)
  }
}

data class OfflineKeyRegParams(
  var `common`: CommonTxnParams,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOfflineKeyRegParams : FfiConverterRustBuffer<OfflineKeyRegParams> {
  override fun read(buf: ByteBuffer): OfflineKeyRegParams =
    OfflineKeyRegParams(
      FfiConverterTypeCommonTxnParams.read(buf),
    )

  override fun allocationSize(value: OfflineKeyRegParams) =
    (
      FfiConverterTypeCommonTxnParams.allocationSize(value.`common`)
    )

  override fun write(
    value: OfflineKeyRegParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeCommonTxnParams.write(value.`common`, buf)
  }
}

data class OnlineKeyRegParams(
  var `common`: CommonTxnParams,
  var `voteKey`: kotlin.ByteArray,
  var `selectionKey`: kotlin.ByteArray,
  var `stateProofKey`: kotlin.ByteArray,
  var `voteFirst`: kotlin.ULong,
  var `voteLast`: kotlin.ULong,
  var `voteKeyDilution`: kotlin.ULong,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOnlineKeyRegParams : FfiConverterRustBuffer<OnlineKeyRegParams> {
  override fun read(buf: ByteBuffer): OnlineKeyRegParams =
    OnlineKeyRegParams(
      FfiConverterTypeCommonTxnParams.read(buf),
      FfiConverterByteArray.read(buf),
      FfiConverterByteArray.read(buf),
      FfiConverterByteArray.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterULong.read(buf),
    )

  override fun allocationSize(value: OnlineKeyRegParams) =
    (
      FfiConverterTypeCommonTxnParams.allocationSize(value.`common`) +
        FfiConverterByteArray.allocationSize(value.`voteKey`) +
        FfiConverterByteArray.allocationSize(value.`selectionKey`) +
        FfiConverterByteArray.allocationSize(value.`stateProofKey`) +
        FfiConverterULong.allocationSize(value.`voteFirst`) +
        FfiConverterULong.allocationSize(value.`voteLast`) +
        FfiConverterULong.allocationSize(value.`voteKeyDilution`)
    )

  override fun write(
    value: OnlineKeyRegParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeCommonTxnParams.write(value.`common`, buf)
    FfiConverterByteArray.write(value.`voteKey`, buf)
    FfiConverterByteArray.write(value.`selectionKey`, buf)
    FfiConverterByteArray.write(value.`stateProofKey`, buf)
    FfiConverterULong.write(value.`voteFirst`, buf)
    FfiConverterULong.write(value.`voteLast`, buf)
    FfiConverterULong.write(value.`voteKeyDilution`, buf)
  }
}

data class PaymentParams(
  var `common`: CommonTxnParams,
  var `receiver`: kotlin.String,
  var `amount`: kotlin.ULong,
  var `closeRemainderTo`: kotlin.String? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePaymentParams : FfiConverterRustBuffer<PaymentParams> {
  override fun read(buf: ByteBuffer): PaymentParams =
    PaymentParams(
      FfiConverterTypeCommonTxnParams.read(buf),
      FfiConverterString.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterOptionalString.read(buf),
    )

  override fun allocationSize(value: PaymentParams) =
    (
      FfiConverterTypeCommonTxnParams.allocationSize(value.`common`) +
        FfiConverterString.allocationSize(value.`receiver`) +
        FfiConverterULong.allocationSize(value.`amount`) +
        FfiConverterOptionalString.allocationSize(value.`closeRemainderTo`)
    )

  override fun write(
    value: PaymentParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeCommonTxnParams.write(value.`common`, buf)
    FfiConverterString.write(value.`receiver`, buf)
    FfiConverterULong.write(value.`amount`, buf)
    FfiConverterOptionalString.write(value.`closeRemainderTo`, buf)
  }
}

data class SimulateOptions(
  /**
   * `None` is treated as `false`. Optional only so the generated bindings get a
   * default-constructible record.
   */
  var `skipSignatures`: kotlin.Boolean? = null,
  var `round`: kotlin.ULong? = null,
  var `allowEmptySignatures`: kotlin.Boolean? = null,
  var `allowMoreLogging`: kotlin.Boolean? = null,
  var `allowUnnamedResources`: kotlin.Boolean? = null,
  var `extraOpcodeBudget`: kotlin.ULong? = null,
  var `execTraceConfig`: SimulateTraceConfig? = null,
  var `fixSigners`: kotlin.Boolean? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSimulateOptions : FfiConverterRustBuffer<SimulateOptions> {
  override fun read(buf: ByteBuffer): SimulateOptions =
    SimulateOptions(
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalTypeSimulateTraceConfig.read(buf),
      FfiConverterOptionalBoolean.read(buf),
    )

  override fun allocationSize(value: SimulateOptions) =
    (
      FfiConverterOptionalBoolean.allocationSize(value.`skipSignatures`) +
        FfiConverterOptionalULong.allocationSize(value.`round`) +
        FfiConverterOptionalBoolean.allocationSize(value.`allowEmptySignatures`) +
        FfiConverterOptionalBoolean.allocationSize(value.`allowMoreLogging`) +
        FfiConverterOptionalBoolean.allocationSize(value.`allowUnnamedResources`) +
        FfiConverterOptionalULong.allocationSize(value.`extraOpcodeBudget`) +
        FfiConverterOptionalTypeSimulateTraceConfig.allocationSize(value.`execTraceConfig`) +
        FfiConverterOptionalBoolean.allocationSize(value.`fixSigners`)
    )

  override fun write(
    value: SimulateOptions,
    buf: ByteBuffer,
  ) {
    FfiConverterOptionalBoolean.write(value.`skipSignatures`, buf)
    FfiConverterOptionalULong.write(value.`round`, buf)
    FfiConverterOptionalBoolean.write(value.`allowEmptySignatures`, buf)
    FfiConverterOptionalBoolean.write(value.`allowMoreLogging`, buf)
    FfiConverterOptionalBoolean.write(value.`allowUnnamedResources`, buf)
    FfiConverterOptionalULong.write(value.`extraOpcodeBudget`, buf)
    FfiConverterOptionalTypeSimulateTraceConfig.write(value.`execTraceConfig`, buf)
    FfiConverterOptionalBoolean.write(value.`fixSigners`, buf)
  }
}

data class SimulateResult(
  /**
   * MsgPack-encoded transactions, index-aligned with `txn_results`.
   */
  var `transactions`: List<kotlin.ByteArray>,
  var `txIds`: List<kotlin.String>,
  var `groupId`: kotlin.ByteArray? = null,
  var `txnResults`: List<SimulateTxnResult>,
  var `failureMessage`: kotlin.String? = null,
  var `failedAt`: List<kotlin.ULong>? = null,
  var `appBudgetAdded`: kotlin.ULong? = null,
  var `appBudgetConsumed`: kotlin.ULong? = null,
  var `lastRound`: kotlin.ULong,
  var `version`: kotlin.ULong,
  /**
   * The complete algod response as msgpack: execution traces, initial states, eval
   * overrides, and anything this record does not flatten.
   */
  var `simulateResponse`: kotlin.ByteArray,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSimulateResult : FfiConverterRustBuffer<SimulateResult> {
  override fun read(buf: ByteBuffer): SimulateResult =
    SimulateResult(
      FfiConverterSequenceByteArray.read(buf),
      FfiConverterSequenceString.read(buf),
      FfiConverterOptionalByteArray.read(buf),
      FfiConverterSequenceTypeSimulateTxnResult.read(buf),
      FfiConverterOptionalString.read(buf),
      FfiConverterOptionalSequenceULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterOptionalULong.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterByteArray.read(buf),
    )

  override fun allocationSize(value: SimulateResult) =
    (
      FfiConverterSequenceByteArray.allocationSize(value.`transactions`) +
        FfiConverterSequenceString.allocationSize(value.`txIds`) +
        FfiConverterOptionalByteArray.allocationSize(value.`groupId`) +
        FfiConverterSequenceTypeSimulateTxnResult.allocationSize(value.`txnResults`) +
        FfiConverterOptionalString.allocationSize(value.`failureMessage`) +
        FfiConverterOptionalSequenceULong.allocationSize(value.`failedAt`) +
        FfiConverterOptionalULong.allocationSize(value.`appBudgetAdded`) +
        FfiConverterOptionalULong.allocationSize(value.`appBudgetConsumed`) +
        FfiConverterULong.allocationSize(value.`lastRound`) +
        FfiConverterULong.allocationSize(value.`version`) +
        FfiConverterByteArray.allocationSize(value.`simulateResponse`)
    )

  override fun write(
    value: SimulateResult,
    buf: ByteBuffer,
  ) {
    FfiConverterSequenceByteArray.write(value.`transactions`, buf)
    FfiConverterSequenceString.write(value.`txIds`, buf)
    FfiConverterOptionalByteArray.write(value.`groupId`, buf)
    FfiConverterSequenceTypeSimulateTxnResult.write(value.`txnResults`, buf)
    FfiConverterOptionalString.write(value.`failureMessage`, buf)
    FfiConverterOptionalSequenceULong.write(value.`failedAt`, buf)
    FfiConverterOptionalULong.write(value.`appBudgetAdded`, buf)
    FfiConverterOptionalULong.write(value.`appBudgetConsumed`, buf)
    FfiConverterULong.write(value.`lastRound`, buf)
    FfiConverterULong.write(value.`version`, buf)
    FfiConverterByteArray.write(value.`simulateResponse`, buf)
  }
}

data class SimulateTraceConfig(
  var `enable`: kotlin.Boolean? = null,
  var `stackChange`: kotlin.Boolean? = null,
  var `scratchChange`: kotlin.Boolean? = null,
  var `stateChange`: kotlin.Boolean? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSimulateTraceConfig : FfiConverterRustBuffer<SimulateTraceConfig> {
  override fun read(buf: ByteBuffer): SimulateTraceConfig =
    SimulateTraceConfig(
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalBoolean.read(buf),
      FfiConverterOptionalBoolean.read(buf),
    )

  override fun allocationSize(value: SimulateTraceConfig) =
    (
      FfiConverterOptionalBoolean.allocationSize(value.`enable`) +
        FfiConverterOptionalBoolean.allocationSize(value.`stackChange`) +
        FfiConverterOptionalBoolean.allocationSize(value.`scratchChange`) +
        FfiConverterOptionalBoolean.allocationSize(value.`stateChange`)
    )

  override fun write(
    value: SimulateTraceConfig,
    buf: ByteBuffer,
  ) {
    FfiConverterOptionalBoolean.write(value.`enable`, buf)
    FfiConverterOptionalBoolean.write(value.`stackChange`, buf)
    FfiConverterOptionalBoolean.write(value.`scratchChange`, buf)
    FfiConverterOptionalBoolean.write(value.`stateChange`, buf)
  }
}

data class SimulateTxnResult(
  var `txId`: kotlin.String,
  /**
   * MsgPack-encoded `PendingTransactionResponse`.
   */
  var `confirmation`: kotlin.ByteArray,
  var `appBudgetConsumed`: kotlin.UInt? = null,
  var `logicSigBudgetConsumed`: kotlin.UInt? = null,
  /**
   * The address algod says should have signed, when `fix_signers` was set.
   */
  var `fixedSigner`: kotlin.String? = null,
  var `logs`: List<kotlin.ByteArray>,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSimulateTxnResult : FfiConverterRustBuffer<SimulateTxnResult> {
  override fun read(buf: ByteBuffer): SimulateTxnResult =
    SimulateTxnResult(
      FfiConverterString.read(buf),
      FfiConverterByteArray.read(buf),
      FfiConverterOptionalUInt.read(buf),
      FfiConverterOptionalUInt.read(buf),
      FfiConverterOptionalString.read(buf),
      FfiConverterSequenceByteArray.read(buf),
    )

  override fun allocationSize(value: SimulateTxnResult) =
    (
      FfiConverterString.allocationSize(value.`txId`) +
        FfiConverterByteArray.allocationSize(value.`confirmation`) +
        FfiConverterOptionalUInt.allocationSize(value.`appBudgetConsumed`) +
        FfiConverterOptionalUInt.allocationSize(value.`logicSigBudgetConsumed`) +
        FfiConverterOptionalString.allocationSize(value.`fixedSigner`) +
        FfiConverterSequenceByteArray.allocationSize(value.`logs`)
    )

  override fun write(
    value: SimulateTxnResult,
    buf: ByteBuffer,
  ) {
    FfiConverterString.write(value.`txId`, buf)
    FfiConverterByteArray.write(value.`confirmation`, buf)
    FfiConverterOptionalUInt.write(value.`appBudgetConsumed`, buf)
    FfiConverterOptionalUInt.write(value.`logicSigBudgetConsumed`, buf)
    FfiConverterOptionalString.write(value.`fixedSigner`, buf)
    FfiConverterSequenceByteArray.write(value.`logs`, buf)
  }
}

data class SuggestedParams(
  var `fee`: kotlin.ULong,
  var `flatFee`: kotlin.Boolean,
  var `firstRoundValid`: kotlin.ULong,
  var `lastRoundValid`: kotlin.ULong,
  var `genesisHash`: kotlin.ByteArray,
  var `genesisId`: kotlin.String,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSuggestedParams : FfiConverterRustBuffer<SuggestedParams> {
  override fun read(buf: ByteBuffer): SuggestedParams =
    SuggestedParams(
      FfiConverterULong.read(buf),
      FfiConverterBoolean.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterULong.read(buf),
      FfiConverterByteArray.read(buf),
      FfiConverterString.read(buf),
    )

  override fun allocationSize(value: SuggestedParams) =
    (
      FfiConverterULong.allocationSize(value.`fee`) +
        FfiConverterBoolean.allocationSize(value.`flatFee`) +
        FfiConverterULong.allocationSize(value.`firstRoundValid`) +
        FfiConverterULong.allocationSize(value.`lastRoundValid`) +
        FfiConverterByteArray.allocationSize(value.`genesisHash`) +
        FfiConverterString.allocationSize(value.`genesisId`)
    )

  override fun write(
    value: SuggestedParams,
    buf: ByteBuffer,
  ) {
    FfiConverterULong.write(value.`fee`, buf)
    FfiConverterBoolean.write(value.`flatFee`, buf)
    FfiConverterULong.write(value.`firstRoundValid`, buf)
    FfiConverterULong.write(value.`lastRoundValid`, buf)
    FfiConverterByteArray.write(value.`genesisHash`, buf)
    FfiConverterString.write(value.`genesisId`, buf)
  }
}

/**
 * Flattened tagged-union for transaction inputs. Exactly one of the variant
 * payload fields must be Some, matching `kind`.
 */
data class TxnParams(
  var `kind`: TxnParamsKind,
  var `payment`: PaymentParams? = null,
  var `assetTransfer`: AssetTransferParams? = null,
  var `assetOptIn`: AssetOptInParams? = null,
  var `onlineKeyReg`: OnlineKeyRegParams? = null,
  var `offlineKeyReg`: OfflineKeyRegParams? = null,
) {
  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxnParams : FfiConverterRustBuffer<TxnParams> {
  override fun read(buf: ByteBuffer): TxnParams =
    TxnParams(
      FfiConverterTypeTxnParamsKind.read(buf),
      FfiConverterOptionalTypePaymentParams.read(buf),
      FfiConverterOptionalTypeAssetTransferParams.read(buf),
      FfiConverterOptionalTypeAssetOptInParams.read(buf),
      FfiConverterOptionalTypeOnlineKeyRegParams.read(buf),
      FfiConverterOptionalTypeOfflineKeyRegParams.read(buf),
    )

  override fun allocationSize(value: TxnParams) =
    (
      FfiConverterTypeTxnParamsKind.allocationSize(value.`kind`) +
        FfiConverterOptionalTypePaymentParams.allocationSize(value.`payment`) +
        FfiConverterOptionalTypeAssetTransferParams.allocationSize(value.`assetTransfer`) +
        FfiConverterOptionalTypeAssetOptInParams.allocationSize(value.`assetOptIn`) +
        FfiConverterOptionalTypeOnlineKeyRegParams.allocationSize(value.`onlineKeyReg`) +
        FfiConverterOptionalTypeOfflineKeyRegParams.allocationSize(value.`offlineKeyReg`)
    )

  override fun write(
    value: TxnParams,
    buf: ByteBuffer,
  ) {
    FfiConverterTypeTxnParamsKind.write(value.`kind`, buf)
    FfiConverterOptionalTypePaymentParams.write(value.`payment`, buf)
    FfiConverterOptionalTypeAssetTransferParams.write(value.`assetTransfer`, buf)
    FfiConverterOptionalTypeAssetOptInParams.write(value.`assetOptIn`, buf)
    FfiConverterOptionalTypeOnlineKeyRegParams.write(value.`onlineKeyReg`, buf)
    FfiConverterOptionalTypeOfflineKeyRegParams.write(value.`offlineKeyReg`, buf)
  }
}

/**
 * FFI-compatible error type for composer operations.
 */
sealed class AlgoKitComposerException : kotlin.Exception() {
  class InvalidAddress(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class InvalidByteLength(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class InvalidTxnParams(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class SignerCountMismatch(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class Signing(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class Transact(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class Algod(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class Msgpack(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class SimulateResponseShape(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class InvalidSimulateOptions(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  class SimulationFailed(
    val `errorMsg`: kotlin.String,
  ) : AlgoKitComposerException() {
    override val message
      get() = "errorMsg=${ `errorMsg` }"
  }

  companion object ErrorHandler : UniffiRustCallStatusErrorHandler<AlgoKitComposerException> {
    override fun lift(error_buf: RustBuffer.ByValue): AlgoKitComposerException = FfiConverterTypeAlgoKitComposerError.lift(error_buf)
  }
}

/**
 * @suppress
 */
public object FfiConverterTypeAlgoKitComposerError : FfiConverterRustBuffer<AlgoKitComposerException> {
  override fun read(buf: ByteBuffer): AlgoKitComposerException =
    when (buf.getInt()) {
      1 -> {
        AlgoKitComposerException.InvalidAddress(
          FfiConverterString.read(buf),
        )
      }

      2 -> {
        AlgoKitComposerException.InvalidByteLength(
          FfiConverterString.read(buf),
        )
      }

      3 -> {
        AlgoKitComposerException.InvalidTxnParams(
          FfiConverterString.read(buf),
        )
      }

      4 -> {
        AlgoKitComposerException.SignerCountMismatch(
          FfiConverterString.read(buf),
        )
      }

      5 -> {
        AlgoKitComposerException.Signing(
          FfiConverterString.read(buf),
        )
      }

      6 -> {
        AlgoKitComposerException.Transact(
          FfiConverterString.read(buf),
        )
      }

      7 -> {
        AlgoKitComposerException.Algod(
          FfiConverterString.read(buf),
        )
      }

      8 -> {
        AlgoKitComposerException.Msgpack(
          FfiConverterString.read(buf),
        )
      }

      9 -> {
        AlgoKitComposerException.SimulateResponseShape(
          FfiConverterString.read(buf),
        )
      }

      10 -> {
        AlgoKitComposerException.InvalidSimulateOptions(
          FfiConverterString.read(buf),
        )
      }

      11 -> {
        AlgoKitComposerException.SimulationFailed(
          FfiConverterString.read(buf),
        )
      }

      else -> {
        throw RuntimeException("invalid error enum value, something is very wrong!!")
      }
    }

  override fun allocationSize(value: AlgoKitComposerException): ULong =
    when (value) {
      is AlgoKitComposerException.InvalidAddress -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.InvalidByteLength -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.InvalidTxnParams -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.SignerCountMismatch -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.Signing -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.Transact -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.Algod -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.Msgpack -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.SimulateResponseShape -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.InvalidSimulateOptions -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )

      is AlgoKitComposerException.SimulationFailed -> (
        // Add the size for the Int that specifies the variant plus the size needed for all fields
        4UL +
          FfiConverterString.allocationSize(value.`errorMsg`)
      )
    }

  override fun write(
    value: AlgoKitComposerException,
    buf: ByteBuffer,
  ) {
    when (value) {
      is AlgoKitComposerException.InvalidAddress -> {
        buf.putInt(1)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.InvalidByteLength -> {
        buf.putInt(2)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.InvalidTxnParams -> {
        buf.putInt(3)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.SignerCountMismatch -> {
        buf.putInt(4)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.Signing -> {
        buf.putInt(5)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.Transact -> {
        buf.putInt(6)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.Algod -> {
        buf.putInt(7)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.Msgpack -> {
        buf.putInt(8)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.SimulateResponseShape -> {
        buf.putInt(9)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.InvalidSimulateOptions -> {
        buf.putInt(10)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }

      is AlgoKitComposerException.SimulationFailed -> {
        buf.putInt(11)
        FfiConverterString.write(value.`errorMsg`, buf)
        Unit
      }
    }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
  }
}

enum class TxnParamsKind {
  PAYMENT,
  ASSET_TRANSFER,
  ASSET_OPT_IN,
  ONLINE_KEY_REG,
  OFFLINE_KEY_REG,
  ;

  companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxnParamsKind : FfiConverterRustBuffer<TxnParamsKind> {
  override fun read(buf: ByteBuffer) =
    try {
      TxnParamsKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
      throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

  override fun allocationSize(value: TxnParamsKind) = 4UL

  override fun write(
    value: TxnParamsKind,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.ordinal + 1)
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalUInt : FfiConverterRustBuffer<kotlin.UInt?> {
  override fun read(buf: ByteBuffer): kotlin.UInt? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterUInt.read(buf)
  }

  override fun allocationSize(value: kotlin.UInt?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterUInt.allocationSize(value)
    }
  }

  override fun write(
    value: kotlin.UInt?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterUInt.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalULong : FfiConverterRustBuffer<kotlin.ULong?> {
  override fun read(buf: ByteBuffer): kotlin.ULong? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterULong.read(buf)
  }

  override fun allocationSize(value: kotlin.ULong?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterULong.allocationSize(value)
    }
  }

  override fun write(
    value: kotlin.ULong?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterULong.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalBoolean : FfiConverterRustBuffer<kotlin.Boolean?> {
  override fun read(buf: ByteBuffer): kotlin.Boolean? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterBoolean.read(buf)
  }

  override fun allocationSize(value: kotlin.Boolean?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterBoolean.allocationSize(value)
    }
  }

  override fun write(
    value: kotlin.Boolean?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterBoolean.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalString : FfiConverterRustBuffer<kotlin.String?> {
  override fun read(buf: ByteBuffer): kotlin.String? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterString.read(buf)
  }

  override fun allocationSize(value: kotlin.String?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterString.allocationSize(value)
    }
  }

  override fun write(
    value: kotlin.String?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterString.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalByteArray : FfiConverterRustBuffer<kotlin.ByteArray?> {
  override fun read(buf: ByteBuffer): kotlin.ByteArray? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterByteArray.read(buf)
  }

  override fun allocationSize(value: kotlin.ByteArray?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterByteArray.allocationSize(value)
    }
  }

  override fun write(
    value: kotlin.ByteArray?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterByteArray.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypeAssetOptInParams : FfiConverterRustBuffer<AssetOptInParams?> {
  override fun read(buf: ByteBuffer): AssetOptInParams? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypeAssetOptInParams.read(buf)
  }

  override fun allocationSize(value: AssetOptInParams?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypeAssetOptInParams.allocationSize(value)
    }
  }

  override fun write(
    value: AssetOptInParams?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypeAssetOptInParams.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypeAssetTransferParams : FfiConverterRustBuffer<AssetTransferParams?> {
  override fun read(buf: ByteBuffer): AssetTransferParams? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypeAssetTransferParams.read(buf)
  }

  override fun allocationSize(value: AssetTransferParams?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypeAssetTransferParams.allocationSize(value)
    }
  }

  override fun write(
    value: AssetTransferParams?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypeAssetTransferParams.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypeOfflineKeyRegParams : FfiConverterRustBuffer<OfflineKeyRegParams?> {
  override fun read(buf: ByteBuffer): OfflineKeyRegParams? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypeOfflineKeyRegParams.read(buf)
  }

  override fun allocationSize(value: OfflineKeyRegParams?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypeOfflineKeyRegParams.allocationSize(value)
    }
  }

  override fun write(
    value: OfflineKeyRegParams?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypeOfflineKeyRegParams.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypeOnlineKeyRegParams : FfiConverterRustBuffer<OnlineKeyRegParams?> {
  override fun read(buf: ByteBuffer): OnlineKeyRegParams? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypeOnlineKeyRegParams.read(buf)
  }

  override fun allocationSize(value: OnlineKeyRegParams?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypeOnlineKeyRegParams.allocationSize(value)
    }
  }

  override fun write(
    value: OnlineKeyRegParams?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypeOnlineKeyRegParams.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypePaymentParams : FfiConverterRustBuffer<PaymentParams?> {
  override fun read(buf: ByteBuffer): PaymentParams? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypePaymentParams.read(buf)
  }

  override fun allocationSize(value: PaymentParams?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypePaymentParams.allocationSize(value)
    }
  }

  override fun write(
    value: PaymentParams?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypePaymentParams.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalTypeSimulateTraceConfig : FfiConverterRustBuffer<SimulateTraceConfig?> {
  override fun read(buf: ByteBuffer): SimulateTraceConfig? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterTypeSimulateTraceConfig.read(buf)
  }

  override fun allocationSize(value: SimulateTraceConfig?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterTypeSimulateTraceConfig.allocationSize(value)
    }
  }

  override fun write(
    value: SimulateTraceConfig?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterTypeSimulateTraceConfig.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterOptionalSequenceULong : FfiConverterRustBuffer<List<kotlin.ULong>?> {
  override fun read(buf: ByteBuffer): List<kotlin.ULong>? {
    if (buf.get().toInt() == 0) {
      return null
    }
    return FfiConverterSequenceULong.read(buf)
  }

  override fun allocationSize(value: List<kotlin.ULong>?): ULong {
    if (value == null) {
      return 1UL
    } else {
      return 1UL + FfiConverterSequenceULong.allocationSize(value)
    }
  }

  override fun write(
    value: List<kotlin.ULong>?,
    buf: ByteBuffer,
  ) {
    if (value == null) {
      buf.put(0)
    } else {
      buf.put(1)
      FfiConverterSequenceULong.write(value, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterSequenceULong : FfiConverterRustBuffer<List<kotlin.ULong>> {
  override fun read(buf: ByteBuffer): List<kotlin.ULong> {
    val len = buf.getInt()
    return List<kotlin.ULong>(len) {
      FfiConverterULong.read(buf)
    }
  }

  override fun allocationSize(value: List<kotlin.ULong>): ULong {
    val sizeForLength = 4UL
    val sizeForItems = value.map { FfiConverterULong.allocationSize(it) }.sum()
    return sizeForLength + sizeForItems
  }

  override fun write(
    value: List<kotlin.ULong>,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    value.iterator().forEach {
      FfiConverterULong.write(it, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterSequenceString : FfiConverterRustBuffer<List<kotlin.String>> {
  override fun read(buf: ByteBuffer): List<kotlin.String> {
    val len = buf.getInt()
    return List<kotlin.String>(len) {
      FfiConverterString.read(buf)
    }
  }

  override fun allocationSize(value: List<kotlin.String>): ULong {
    val sizeForLength = 4UL
    val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
    return sizeForLength + sizeForItems
  }

  override fun write(
    value: List<kotlin.String>,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    value.iterator().forEach {
      FfiConverterString.write(it, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterSequenceByteArray : FfiConverterRustBuffer<List<kotlin.ByteArray>> {
  override fun read(buf: ByteBuffer): List<kotlin.ByteArray> {
    val len = buf.getInt()
    return List<kotlin.ByteArray>(len) {
      FfiConverterByteArray.read(buf)
    }
  }

  override fun allocationSize(value: List<kotlin.ByteArray>): ULong {
    val sizeForLength = 4UL
    val sizeForItems = value.map { FfiConverterByteArray.allocationSize(it) }.sum()
    return sizeForLength + sizeForItems
  }

  override fun write(
    value: List<kotlin.ByteArray>,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    value.iterator().forEach {
      FfiConverterByteArray.write(it, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterSequenceTypeSimulateTxnResult : FfiConverterRustBuffer<List<SimulateTxnResult>> {
  override fun read(buf: ByteBuffer): List<SimulateTxnResult> {
    val len = buf.getInt()
    return List<SimulateTxnResult>(len) {
      FfiConverterTypeSimulateTxnResult.read(buf)
    }
  }

  override fun allocationSize(value: List<SimulateTxnResult>): ULong {
    val sizeForLength = 4UL
    val sizeForItems = value.map { FfiConverterTypeSimulateTxnResult.allocationSize(it) }.sum()
    return sizeForLength + sizeForItems
  }

  override fun write(
    value: List<SimulateTxnResult>,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    value.iterator().forEach {
      FfiConverterTypeSimulateTxnResult.write(it, buf)
    }
  }
}

/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxnParams : FfiConverterRustBuffer<List<TxnParams>> {
  override fun read(buf: ByteBuffer): List<TxnParams> {
    val len = buf.getInt()
    return List<TxnParams>(len) {
      FfiConverterTypeTxnParams.read(buf)
    }
  }

  override fun allocationSize(value: List<TxnParams>): ULong {
    val sizeForLength = 4UL
    val sizeForItems = value.map { FfiConverterTypeTxnParams.allocationSize(it) }.sum()
    return sizeForLength + sizeForItems
  }

  override fun write(
    value: List<TxnParams>,
    buf: ByteBuffer,
  ) {
    buf.putInt(value.size)
    value.iterator().forEach {
      FfiConverterTypeTxnParams.write(it, buf)
    }
  }
}

/**
 * Encode a simulate request for an already-signed group. Signatures are preserved unless
 * `options.skip_signatures` is set.
 */
@Throws(AlgoKitComposerException::class)
fun `buildSignedSimulateRequest`(
  `signedTransactions`: List<kotlin.ByteArray>,
  `options`: SimulateOptions,
): kotlin.ByteArray =
  FfiConverterByteArray.lift(
    uniffiRustCallWithError(AlgoKitComposerException) { _status ->
      UniffiLib.INSTANCE.uniffi_algokit_composer_ffi_fn_func_build_signed_simulate_request(
        FfiConverterSequenceByteArray.lower(`signedTransactions`),
        FfiConverterTypeSimulateOptions.lower(`options`),
        _status,
      )
    },
  )

/**
 * Wrap unsigned transactions in signature-less envelopes and encode the simulate request
 * body, ready to POST to `/v2/transactions/simulate?format=msgpack` with `Content-Type`
 * and `Accept` both `application/msgpack`.
 */
@Throws(AlgoKitComposerException::class)
fun `buildUnsignedSimulateRequest`(
  `transactions`: List<kotlin.ByteArray>,
  `options`: SimulateOptions,
): kotlin.ByteArray =
  FfiConverterByteArray.lift(
    uniffiRustCallWithError(AlgoKitComposerException) { _status ->
      UniffiLib.INSTANCE.uniffi_algokit_composer_ffi_fn_func_build_unsigned_simulate_request(
        FfiConverterSequenceByteArray.lower(`transactions`),
        FfiConverterTypeSimulateOptions.lower(`options`),
        _status,
      )
    },
  )

/**
 * Build transactions from the supplied TxnParams list using composer-level
 * defaults. Returns each transaction encoded to MsgPack bytes. When the input
 * has more than one entry the results are atomically grouped (shared group ID).
 */
@Throws(AlgoKitComposerException::class)
fun `compose`(
  `txnParams`: List<TxnParams>,
  `composerParams`: ComposerParams,
): List<kotlin.ByteArray> =
  FfiConverterSequenceByteArray.lift(
    uniffiRustCallWithError(AlgoKitComposerException) { _status ->
      UniffiLib.INSTANCE.uniffi_algokit_composer_ffi_fn_func_compose(
        FfiConverterSequenceTypeTxnParams.lower(`txnParams`),
        FfiConverterTypeComposerParams.lower(`composerParams`),
        _status,
      )
    },
  )

/**
 * Map a raw msgpack simulate response onto a structured result.
 *
 * `transactions` is the list the request was built from, passed explicitly rather than
 * recovered from the request body.
 */
@Throws(AlgoKitComposerException::class)
fun `mapSimulateResponse`(
  `transactions`: List<kotlin.ByteArray>,
  `response`: kotlin.ByteArray,
): SimulateResult =
  FfiConverterTypeSimulateResult.lift(
    uniffiRustCallWithError(AlgoKitComposerException) { _status ->
      UniffiLib.INSTANCE.uniffi_algokit_composer_ffi_fn_func_map_simulate_response(
        FfiConverterSequenceByteArray.lower(`transactions`),
        FfiConverterByteArray.lower(`response`),
        _status,
      )
    },
  )

/**
 * Sign each MsgPack-encoded transaction with the corresponding 32-byte Ed25519
 * secret key and return the encoded signed transactions ready for submission.
 */
@Throws(AlgoKitComposerException::class)
fun `signTransactions`(
  `transactionBytes`: List<kotlin.ByteArray>,
  `secretKeys`: List<kotlin.ByteArray>,
): List<kotlin.ByteArray> =
  FfiConverterSequenceByteArray.lift(
    uniffiRustCallWithError(AlgoKitComposerException) { _status ->
      UniffiLib.INSTANCE.uniffi_algokit_composer_ffi_fn_func_sign_transactions(
        FfiConverterSequenceByteArray.lower(`transactionBytes`),
        FfiConverterSequenceByteArray.lower(`secretKeys`),
        _status,
      )
    },
  )
