/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use super::{configuration, Error};
use crate::models::{
    AbortCatchup200Response, Account, AccountApplicationInformation200Response,
    AccountAssetInformation200Response, AccountAssetsInformation200Response,
    AddParticipationKey200Response, Application, Asset, DebugSettingsProf, DryrunRequest,
    ErrorResponse, Genesis, GetApplicationBoxes200Response, GetBlock200Response,
    GetBlockHash200Response, GetBlockLogs200Response, GetBlockTimeStampOffset200Response,
    GetBlockTxids200Response, GetPendingTransactions200Response,
    GetPendingTransactionsByAddress200Response, GetStatus200Response, GetSupply200Response,
    GetSyncRound200Response, GetTransactionGroupLedgerStateDeltasForRound200Response,
    GetTransactionProof200Response, LedgerStateDelta, LightBlockHeaderProof, ModelBox,
    ParticipationKey, PendingTransactionResponse, RawTransaction200Response, SimulateRequest,
    SimulateTransaction200Response, StartCatchup200Response, StartCatchup201Response, StateProof,
    TealCompile200Response, TealDisassemble200Response, TealDryrun200Response,
    TransactionParams200Response, Version, WaitForBlock200Response,
};

/// The main Algod API client.
///
/// This client provides convenient access to all Algod API endpoints.
/// It wraps the lower-level endpoint functions with a more ergonomic interface.
#[derive(Debug, Clone)]
pub struct AlgodClient {
    configuration: configuration::Configuration,
}

impl AlgodClient {
    /// Create a new AlgodClient with custom configuration.
    pub fn new(configuration: configuration::Configuration) -> Self {
        Self { configuration }
    }

    /// Create a new AlgodClient with a custom base URL and optional API token.
    pub fn with_url(base_url: &str, api_token: Option<&str>) -> Self {
        let mut config = configuration::Configuration::default();
        config.base_path = base_url.trim_end_matches('/').to_string();

        if let Some(token) = api_token {
            config.api_key = Some(configuration::ApiKey {
                prefix: None,
                key: token.to_string(),
            });
        }

        Self::new(config)
    }

    /// Create a new AlgodClient for Algorand TestNet.
    pub fn testnet() -> Self {
        Self::with_url("https://testnet-api.4160.nodely.dev", None)
    }

    /// Create a new AlgodClient for Algorand MainNet.
    pub fn mainnet() -> Self {
        Self::with_url("https://mainnet-api.4160.nodely.dev", None)
    }

    /// Create a new AlgodClient for a local sandbox environment.
    pub fn sandbox() -> Self {
        Self::with_url(
            "http://localhost:4001",
            Some("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
        )
    }

    /// Get a reference to the underlying configuration.
    pub fn configuration(&self) -> &configuration::Configuration {
        &self.configuration
    }

    /// Get a mutable reference to the underlying configuration.
    pub fn configuration_mut(&mut self) -> &mut configuration::Configuration {
        &mut self.configuration
    }

    /// Returns OK if healthy.
    pub async fn health_check(&self) -> Result<(), Error<super::health_check::HealthCheckError>> {
        super::health_check::health_check(&self.configuration).await
    }

    /// Returns OK if healthy and fully caught up.
    pub async fn get_ready(&self) -> Result<(), Error<super::get_ready::GetReadyError>> {
        super::get_ready::get_ready(&self.configuration).await
    }

    /// Return metrics about algod functioning.
    pub async fn metrics(&self) -> Result<(), Error<super::metrics::MetricsError>> {
        super::metrics::metrics(&self.configuration).await
    }

    /// Gets the genesis information.
    pub async fn get_genesis(&self) -> Result<Genesis, Error<super::get_genesis::GetGenesisError>> {
        super::get_genesis::get_genesis(&self.configuration).await
    }

    /// Gets the current swagger spec.
    pub async fn swagger_j_s_o_n(
        &self,
    ) -> Result<String, Error<super::swagger_j_s_o_n::SwaggerJsonError>> {
        super::swagger_j_s_o_n::swagger_j_s_o_n(&self.configuration).await
    }

    /// Retrieves the supported API versions, binary build versions, and genesis information.
    pub async fn get_version(&self) -> Result<Version, Error<super::get_version::GetVersionError>> {
        super::get_version::get_version(&self.configuration).await
    }

    /// Retrieves the current settings for blocking and mutex profiles
    pub async fn get_debug_settings_prof(
        &self,
    ) -> Result<DebugSettingsProf, Error<super::get_debug_settings_prof::GetDebugSettingsProfError>>
    {
        super::get_debug_settings_prof::get_debug_settings_prof(&self.configuration).await
    }

    /// Enables blocking and mutex profiles, and returns the old settings
    pub async fn put_debug_settings_prof(
        &self,
    ) -> Result<DebugSettingsProf, Error<super::put_debug_settings_prof::PutDebugSettingsProfError>>
    {
        super::put_debug_settings_prof::put_debug_settings_prof(&self.configuration).await
    }

    /// Gets the merged config file.
    pub async fn get_config(&self) -> Result<String, Error<super::get_config::GetConfigError>> {
        super::get_config::get_config(&self.configuration).await
    }

    /// Get account information.
    pub async fn account_information(
        &self,
        format: Option<&str>,
        address: &str,
        exclude: Option<&str>,
    ) -> Result<Account, Error<super::account_information::AccountInformationError>> {
        super::account_information::account_information(
            &self.configuration,
            format,
            address,
            exclude,
        )
        .await
    }

    /// Get account information about a given asset.
    pub async fn account_asset_information(
        &self,
        format: Option<&str>,
        address: &str,
        asset_id: i32,
    ) -> Result<
        AccountAssetInformation200Response,
        Error<super::account_asset_information::AccountAssetInformationError>,
    > {
        super::account_asset_information::account_asset_information(
            &self.configuration,
            format,
            address,
            asset_id,
        )
        .await
    }

    /// Get a list of assets held by an account, inclusive of asset params.
    pub async fn account_assets_information(
        &self,
        address: &str,
        limit: Option<i32>,
        next: Option<&str>,
    ) -> Result<
        AccountAssetsInformation200Response,
        Error<super::account_assets_information::AccountAssetsInformationError>,
    > {
        super::account_assets_information::account_assets_information(
            &self.configuration,
            address,
            limit,
            next,
        )
        .await
    }

    /// Get account information about a given app.
    pub async fn account_application_information(
        &self,
        format: Option<&str>,
        address: &str,
        application_id: i32,
    ) -> Result<
        AccountApplicationInformation200Response,
        Error<super::account_application_information::AccountApplicationInformationError>,
    > {
        super::account_application_information::account_application_information(
            &self.configuration,
            format,
            address,
            application_id,
        )
        .await
    }

    /// Get a list of unconfirmed transactions currently in the transaction pool by address.
    pub async fn get_pending_transactions_by_address(
        &self,
        address: &str,
        max: Option<i32>,
        format: Option<&str>,
    ) -> Result<
        GetPendingTransactionsByAddress200Response,
        Error<super::get_pending_transactions_by_address::GetPendingTransactionsByAddressError>,
    > {
        super::get_pending_transactions_by_address::get_pending_transactions_by_address(
            &self.configuration,
            address,
            max,
            format,
        )
        .await
    }

    /// Get the block for the given round.
    pub async fn get_block(
        &self,
        format: Option<&str>,
        round: i32,
        header_only: Option<bool>,
    ) -> Result<GetBlock200Response, Error<super::get_block::GetBlockError>> {
        super::get_block::get_block(&self.configuration, format, round, header_only).await
    }

    /// Get the top level transaction IDs for the block on the given round.
    pub async fn get_block_txids(
        &self,
        round: i32,
    ) -> Result<GetBlockTxids200Response, Error<super::get_block_txids::GetBlockTxidsError>> {
        super::get_block_txids::get_block_txids(&self.configuration, round).await
    }

    /// Get the block hash for the block on the given round.
    pub async fn get_block_hash(
        &self,
        round: i32,
    ) -> Result<GetBlockHash200Response, Error<super::get_block_hash::GetBlockHashError>> {
        super::get_block_hash::get_block_hash(&self.configuration, round).await
    }

    /// Get a proof for a transaction in a block.
    pub async fn get_transaction_proof(
        &self,
        round: i32,
        txid: &str,
        hashtype: Option<&str>,
        format: Option<&str>,
    ) -> Result<
        GetTransactionProof200Response,
        Error<super::get_transaction_proof::GetTransactionProofError>,
    > {
        super::get_transaction_proof::get_transaction_proof(
            &self.configuration,
            round,
            txid,
            hashtype,
            format,
        )
        .await
    }

    /// Get all of the logs from outer and inner app calls in the given round
    pub async fn get_block_logs(
        &self,
        round: i32,
    ) -> Result<GetBlockLogs200Response, Error<super::get_block_logs::GetBlockLogsError>> {
        super::get_block_logs::get_block_logs(&self.configuration, round).await
    }

    /// Get the current supply reported by the ledger.
    pub async fn get_supply(
        &self,
    ) -> Result<GetSupply200Response, Error<super::get_supply::GetSupplyError>> {
        super::get_supply::get_supply(&self.configuration).await
    }

    /// Return a list of participation keys
    pub async fn get_participation_keys(
        &self,
    ) -> Result<
        Vec<ParticipationKey>,
        Error<super::get_participation_keys::GetParticipationKeysError>,
    > {
        super::get_participation_keys::get_participation_keys(&self.configuration).await
    }

    /// Add a participation key to the node
    pub async fn add_participation_key(
        &self,
        request: Vec<u8>,
    ) -> Result<
        AddParticipationKey200Response,
        Error<super::add_participation_key::AddParticipationKeyError>,
    > {
        super::add_participation_key::add_participation_key(&self.configuration, request).await
    }

    /// Generate and install participation keys to the node.
    pub async fn generate_participation_keys(
        &self,
        address: &str,
        dilution: Option<i32>,
        first: i32,
        last: i32,
    ) -> Result<String, Error<super::generate_participation_keys::GenerateParticipationKeysError>>
    {
        super::generate_participation_keys::generate_participation_keys(
            &self.configuration,
            address,
            dilution,
            first,
            last,
        )
        .await
    }

    /// Get participation key info given a participation ID
    pub async fn get_participation_key_by_i_d(
        &self,
        participation_id: &str,
    ) -> Result<
        ParticipationKey,
        Error<super::get_participation_key_by_i_d::GetParticipationKeyByIdError>,
    > {
        super::get_participation_key_by_i_d::get_participation_key_by_i_d(
            &self.configuration,
            participation_id,
        )
        .await
    }

    /// Append state proof keys to a participation key
    pub async fn append_keys(
        &self,
        request: Vec<u8>,
        participation_id: &str,
    ) -> Result<ParticipationKey, Error<super::append_keys::AppendKeysError>> {
        super::append_keys::append_keys(&self.configuration, request, participation_id).await
    }

    /// Delete a given participation key by ID
    pub async fn delete_participation_key_by_i_d(
        &self,
        participation_id: &str,
    ) -> Result<(), Error<super::delete_participation_key_by_i_d::DeleteParticipationKeyByIdError>>
    {
        super::delete_participation_key_by_i_d::delete_participation_key_by_i_d(
            &self.configuration,
            participation_id,
        )
        .await
    }

    /// Special management endpoint to shutdown the node. Optionally provide a timeout parameter to indicate that the node should begin shutting down after a number of seconds.
    pub async fn shutdown_node(
        &self,
        timeout: Option<i32>,
    ) -> Result<serde_json::Value, Error<super::shutdown_node::ShutdownNodeError>> {
        super::shutdown_node::shutdown_node(&self.configuration, timeout).await
    }

    /// Gets the current node status.
    pub async fn get_status(
        &self,
    ) -> Result<GetStatus200Response, Error<super::get_status::GetStatusError>> {
        super::get_status::get_status(&self.configuration).await
    }

    /// Gets the node status after waiting for a round after the given round.
    pub async fn wait_for_block(
        &self,
        round: i32,
    ) -> Result<WaitForBlock200Response, Error<super::wait_for_block::WaitForBlockError>> {
        super::wait_for_block::wait_for_block(&self.configuration, round).await
    }

    /// Broadcasts a raw transaction or transaction group to the network.
    pub async fn raw_transaction(
        &self,
        request: Vec<u8>,
    ) -> Result<RawTransaction200Response, Error<super::raw_transaction::RawTransactionError>> {
        super::raw_transaction::raw_transaction(&self.configuration, request).await
    }

    /// Fast track for broadcasting a raw transaction or transaction group to the network through the tx handler without performing most of the checks and reporting detailed errors. Should be only used for development and performance testing.
    pub async fn raw_transaction_async(
        &self,
        request: Vec<u8>,
    ) -> Result<(), Error<super::raw_transaction_async::RawTransactionAsyncError>> {
        super::raw_transaction_async::raw_transaction_async(&self.configuration, request).await
    }

    /// Simulates a raw transaction or transaction group as it would be evaluated on the network. The simulation will use blockchain state from the latest committed round.
    pub async fn simulate_transaction(
        &self,
        request: SimulateRequest,
        format: Option<&str>,
    ) -> Result<
        SimulateTransaction200Response,
        Error<super::simulate_transaction::SimulateTransactionError>,
    > {
        super::simulate_transaction::simulate_transaction(&self.configuration, request, format)
            .await
    }

    /// Get parameters for constructing a new transaction
    pub async fn transaction_params(
        &self,
    ) -> Result<
        TransactionParams200Response,
        Error<super::transaction_params::TransactionParamsError>,
    > {
        super::transaction_params::transaction_params(&self.configuration).await
    }

    /// Get a list of unconfirmed transactions currently in the transaction pool.
    pub async fn get_pending_transactions(
        &self,
        max: Option<i32>,
        format: Option<&str>,
    ) -> Result<
        GetPendingTransactions200Response,
        Error<super::get_pending_transactions::GetPendingTransactionsError>,
    > {
        super::get_pending_transactions::get_pending_transactions(&self.configuration, max, format)
            .await
    }

    /// Get a specific pending transaction.
    pub async fn pending_transaction_information(
        &self,
        txid: &str,
        format: Option<&str>,
    ) -> Result<
        PendingTransactionResponse,
        Error<super::pending_transaction_information::PendingTransactionInformationError>,
    > {
        super::pending_transaction_information::pending_transaction_information(
            &self.configuration,
            txid,
            format,
        )
        .await
    }

    /// Get a LedgerStateDelta object for a given round
    pub async fn get_ledger_state_delta(
        &self,
        round: i32,
        format: Option<&str>,
    ) -> Result<LedgerStateDelta, Error<super::get_ledger_state_delta::GetLedgerStateDeltaError>>
    {
        super::get_ledger_state_delta::get_ledger_state_delta(&self.configuration, round, format)
            .await
    }

    /// Get LedgerStateDelta objects for all transaction groups in a given round
    pub async fn get_transaction_group_ledger_state_deltas_for_round(
        &self,
round: i32,
format: Option<&str>,
    ) -> Result<GetTransactionGroupLedgerStateDeltasForRound200Response, Error<super::get_transaction_group_ledger_state_deltas_for_round::GetTransactionGroupLedgerStateDeltasForRoundError>>{
        super::get_transaction_group_ledger_state_deltas_for_round::get_transaction_group_ledger_state_deltas_for_round(
            &self.configuration,
            round,
            format,
        ).await
    }

    /// Get a LedgerStateDelta object for a given transaction group
    pub async fn get_ledger_state_delta_for_transaction_group(
        &self,
id: &str,
format: Option<&str>,
    ) -> Result<LedgerStateDelta, Error<super::get_ledger_state_delta_for_transaction_group::GetLedgerStateDeltaForTransactionGroupError>>{
        super::get_ledger_state_delta_for_transaction_group::get_ledger_state_delta_for_transaction_group(
            &self.configuration,
            id,
            format,
        ).await
    }

    /// Get a state proof that covers a given round
    pub async fn get_state_proof(
        &self,
        round: i32,
    ) -> Result<StateProof, Error<super::get_state_proof::GetStateProofError>> {
        super::get_state_proof::get_state_proof(&self.configuration, round).await
    }

    /// Gets a proof for a given light block header inside a state proof commitment
    pub async fn get_light_block_header_proof(
        &self,
        round: i32,
    ) -> Result<
        LightBlockHeaderProof,
        Error<super::get_light_block_header_proof::GetLightBlockHeaderProofError>,
    > {
        super::get_light_block_header_proof::get_light_block_header_proof(
            &self.configuration,
            round,
        )
        .await
    }

    /// Get application information.
    pub async fn get_application_by_i_d(
        &self,
        application_id: i32,
    ) -> Result<Application, Error<super::get_application_by_i_d::GetApplicationByIdError>> {
        super::get_application_by_i_d::get_application_by_i_d(&self.configuration, application_id)
            .await
    }

    /// Get all box names for a given application.
    pub async fn get_application_boxes(
        &self,
        application_id: i32,
        max: Option<i32>,
    ) -> Result<
        GetApplicationBoxes200Response,
        Error<super::get_application_boxes::GetApplicationBoxesError>,
    > {
        super::get_application_boxes::get_application_boxes(
            &self.configuration,
            application_id,
            max,
        )
        .await
    }

    /// Get box information for a given application.
    pub async fn get_application_box_by_name(
        &self,
        application_id: i32,
        name: &str,
    ) -> Result<ModelBox, Error<super::get_application_box_by_name::GetApplicationBoxByNameError>>
    {
        super::get_application_box_by_name::get_application_box_by_name(
            &self.configuration,
            application_id,
            name,
        )
        .await
    }

    /// Get asset information.
    pub async fn get_asset_by_i_d(
        &self,
        asset_id: i32,
    ) -> Result<Asset, Error<super::get_asset_by_i_d::GetAssetByIdError>> {
        super::get_asset_by_i_d::get_asset_by_i_d(&self.configuration, asset_id).await
    }

    /// Returns the minimum sync round the ledger is keeping in cache.
    pub async fn get_sync_round(
        &self,
    ) -> Result<GetSyncRound200Response, Error<super::get_sync_round::GetSyncRoundError>> {
        super::get_sync_round::get_sync_round(&self.configuration).await
    }

    /// Removes minimum sync round restriction from the ledger.
    pub async fn unset_sync_round(
        &self,
    ) -> Result<(), Error<super::unset_sync_round::UnsetSyncRoundError>> {
        super::unset_sync_round::unset_sync_round(&self.configuration).await
    }

    /// Given a round, tells the ledger to keep that round in its cache.
    pub async fn set_sync_round(
        &self,
        round: i32,
    ) -> Result<(), Error<super::set_sync_round::SetSyncRoundError>> {
        super::set_sync_round::set_sync_round(&self.configuration, round).await
    }

    /// Compile TEAL source code to binary, produce its hash
    pub async fn teal_compile(
        &self,
        request: Vec<u8>,
        sourcemap: Option<bool>,
    ) -> Result<TealCompile200Response, Error<super::teal_compile::TealCompileError>> {
        super::teal_compile::teal_compile(&self.configuration, request, sourcemap).await
    }

    /// Disassemble program bytes into the TEAL source code.
    pub async fn teal_disassemble(
        &self,
        request: String,
    ) -> Result<TealDisassemble200Response, Error<super::teal_disassemble::TealDisassembleError>>
    {
        super::teal_disassemble::teal_disassemble(&self.configuration, request).await
    }

    /// Starts a catchpoint catchup.
    pub async fn start_catchup(
        &self,
        catchpoint: &str,
        min: Option<i32>,
    ) -> Result<StartCatchup200Response, Error<super::start_catchup::StartCatchupError>> {
        super::start_catchup::start_catchup(&self.configuration, catchpoint, min).await
    }

    /// Aborts a catchpoint catchup.
    pub async fn abort_catchup(
        &self,
        catchpoint: &str,
    ) -> Result<AbortCatchup200Response, Error<super::abort_catchup::AbortCatchupError>> {
        super::abort_catchup::abort_catchup(&self.configuration, catchpoint).await
    }

    /// Provide debugging information for a transaction (or group).
    pub async fn teal_dryrun(
        &self,
        request: Option<DryrunRequest>,
    ) -> Result<TealDryrun200Response, Error<super::teal_dryrun::TealDryrunError>> {
        super::teal_dryrun::teal_dryrun(&self.configuration, request).await
    }

    /// Returns OK if experimental API is enabled.
    pub async fn experimental_check(
        &self,
    ) -> Result<(), Error<super::experimental_check::ExperimentalCheckError>> {
        super::experimental_check::experimental_check(&self.configuration).await
    }

    /// Returns the timestamp offset. Timestamp offsets can only be set in dev mode.
    pub async fn get_block_time_stamp_offset(
        &self,
    ) -> Result<
        GetBlockTimeStampOffset200Response,
        Error<super::get_block_time_stamp_offset::GetBlockTimeStampOffsetError>,
    > {
        super::get_block_time_stamp_offset::get_block_time_stamp_offset(&self.configuration).await
    }

    /// Given a timestamp offset in seconds, adds the offset to every subsequent block header's timestamp.
    pub async fn set_block_time_stamp_offset(
        &self,
        offset: i32,
    ) -> Result<(), Error<super::set_block_time_stamp_offset::SetBlockTimeStampOffsetError>> {
        super::set_block_time_stamp_offset::set_block_time_stamp_offset(&self.configuration, offset)
            .await
    }
}

impl Default for AlgodClient {
    fn default() -> Self {
        Self::new(configuration::Configuration::default())
    }
}
