/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

// Import response types for this endpoint
use crate::models::{
    GetTransactionGroupLedgerStateDeltasForRound200Response,
};

/// struct for typed errors of method [`get_transaction_group_ledger_state_deltas_for_round`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTransactionGroupLedgerStateDeltasForRoundError {
    Status401(serde_json::Value),
    Status404(serde_json::Value),
    Status408(serde_json::Value),
    Status500(serde_json::Value),
    Status501(serde_json::Value),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// Get ledger deltas for transaction groups in a given round.
pub async fn get_transaction_group_ledger_state_deltas_for_round(
    configuration: &configuration::Configuration,
round: i32,
format: Option<&str>,
) -> Result<GetTransactionGroupLedgerStateDeltasForRound200Response, Error<GetTransactionGroupLedgerStateDeltasForRoundError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_round = round;
    let p_format = format;

    let uri_str = format!("{}/v2/deltas/{round}/txn/group", configuration.base_path, round=p_round);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Algo-API-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        match content_type {
            ContentType::Json => {
                let content = resp.text().await?;
                serde_json::from_str(&content).map_err(Error::from)
            },
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `GetTransactionGroupLedgerStateDeltasForRound200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `GetTransactionGroupLedgerStateDeltasForRound200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTransactionGroupLedgerStateDeltasForRoundError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}