/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

// Import all custom types used by this endpoint
use crate::models::{
    ErrorResponse,
};

// Import request body type if needed

/// struct for typed errors of method [`set_block_time_stamp_offset`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetBlockTimeStampOffsetError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// Sets the timestamp offset (seconds) for blocks in dev mode. Providing an offset of 0 will unset this value and try to use the real clock for the timestamp.
pub async fn set_block_time_stamp_offset(
    configuration: &configuration::Configuration,
offset: i32,

) -> Result<(), Error<SetBlockTimeStampOffsetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_offset = offset;

    let uri_str = format!("{}/v2/devmode/blocks/offset/{offset}", configuration.base_path, offset=p_offset);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);



    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Algo-API-Token", value);
    };


    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let _content = resp.text().await?;
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SetBlockTimeStampOffsetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}