/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};
use algokit_transact::AlgorandMsgpack;

// Import all custom types used by this endpoint
use crate::models::{
    ErrorResponse,
    TealDryrun200Response,
};

// Import request body type if needed
use crate::models::DryrunRequest;

/// struct for typed errors of method [`teal_dryrun`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TealDryrunError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// Executes TEAL program(s) in context and returns debugging information about the execution. This endpoint is only enabled when a node's configuration file sets EnableDeveloperAPI to true.
pub async fn teal_dryrun(
    configuration: &configuration::Configuration,
request: Option<DryrunRequest>,

) -> Result<TealDryrun200Response, Error<TealDryrunError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_request = request;

    let uri_str = format!("{}/v2/teal/dryrun", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);



    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Algo-API-Token", value);
    };

    // Determine content type: use msgpack by default if supported, unless format explicitly requests JSON
    let use_msgpack = true;

    if let Some(ref request_body) = p_request {
        if use_msgpack {
            // Serialize using msgpack
            let msgpack_bytes = request_body.encode()
                .map_err(|e| Error::from(serde_json::Error::custom(format!("Failed to serialize to msgpack: {}", e))))?;
            req_builder = req_builder
                .header("Content-Type", "application/msgpack")
                .body(msgpack_bytes);
        } else {
            // Use JSON
            req_builder = req_builder.json(request_body);
        }
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        match content_type {
            ContentType::Json => {
                let content = resp.text().await?;
                serde_json::from_str(&content).map_err(Error::from)
            },
            ContentType::MsgPack => {
                return Err(Error::from(serde_json::Error::custom("MsgPack response handling not supported for this endpoint")))
            },
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `TealDryrun200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `TealDryrun200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TealDryrunError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}