/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Apiv1Wallet;

/// APIV1WalletHandle includes the wallet the handle corresponds to
/// and the number of number of seconds to expiration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct Apiv1WalletHandle {
    #[serde(rename = "expires_seconds", skip_serializing_if = "Option::is_none")]
    pub expires_seconds: Option<u64>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Apiv1Wallet>,
}

impl Apiv1WalletHandle {
    /// Default constructor for Apiv1WalletHandle
    pub fn new() -> Apiv1WalletHandle {
        Apiv1WalletHandle::default()
    }
}
