/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::MasterDerivationKey;

/// APIV1POSTMasterKeyExportResponse is the response to `POST /v1/master-key/export`
/// friendly:ExportMasterKeyResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct Apiv1PostMasterKeyExportResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(
        rename = "master_derivation_key",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_derivation_key: Option<MasterDerivationKey>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl Apiv1PostMasterKeyExportResponse {
    /// Default constructor for Apiv1PostMasterKeyExportResponse
    pub fn new() -> Apiv1PostMasterKeyExportResponse {
        Apiv1PostMasterKeyExportResponse::default()
    }
}
