/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// APIV1POSTKeyImportResponse is the response to `POST /v1/key/import`
/// friendly:ImportKeyResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct Apiv1PostKeyImportResponse {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl Apiv1PostKeyImportResponse {
    /// Default constructor for Apiv1PostKeyImportResponse
    pub fn new() -> Apiv1PostKeyImportResponse {
        Apiv1PostKeyImportResponse::default()
    }
}
