/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};




/// An catchpoint abort response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbortCatchup200Response {
        /// Catchup abort response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}



impl AlgorandMsgpack for AbortCatchup200Response {
    const PREFIX: &'static [u8] = b"";  // Adjust prefix as needed for your specific type
}

impl AbortCatchup200Response {
    /// Constructor for AbortCatchup200Response
    pub fn new(catchup_message: String) -> AbortCatchup200Response {
        AbortCatchup200Response {
            catchup_message,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
