/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// An catchpoint abort response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbortCatchup200Response {
        /// Catchup abort response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}



impl AbortCatchup200Response {
    /// Constructor for AbortCatchup200Response
    pub fn new(catchup_message: String) -> AbortCatchup200Response {
        AbortCatchup200Response {
            catchup_message,
        }
    }
}
