/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::ApplicationLocalState;
use crate::models::ApplicationParams;

/// AccountApplicationResponse describes the account's application local state and global state (AppLocalState and AppParams, if either exists) for a specific application ID. Global state will only be returned if the provided address is the application's creator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountApplicationInformation {
    /// The round for which this information is relevant.
    #[serde(rename = "round")]
    pub round: u64,
    #[serde(rename = "app-local-state", skip_serializing_if = "Option::is_none")]
    pub app_local_state: Option<ApplicationLocalState>,
    #[serde(rename = "created-app", skip_serializing_if = "Option::is_none")]
    pub created_app: Option<ApplicationParams>,
}

impl AccountApplicationInformation {
    /// Constructor for AccountApplicationInformation
    pub fn new(round: u64) -> AccountApplicationInformation {
        AccountApplicationInformation {
            round,
            app_local_state: None,
            created_app: None,
        }
    }
}
