/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountAssetHolding describes the account's asset holding and asset parameters (if either exist) for a specific asset ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAssetHolding {
    #[serde(rename = "asset-holding")]
    pub asset_holding: serde_json::Value,
    #[serde(rename = "asset-params", skip_serializing_if = "Option::is_none")]
    pub asset_params: Option<serde_json::Value>,
}



impl AccountAssetHolding {
    /// Constructor for AccountAssetHolding
    pub fn new(asset_holding: serde_json::Value) -> AccountAssetHolding {
        AccountAssetHolding {
            asset_holding,
            asset_params: None,
        }
    }
}
