/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountAssetResponse describes the account's asset holding and asset parameters (if either exist) for a specific asset ID. Asset parameters will only be returned if the provided address is the asset's creator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAssetInformation200Response {
        /// The round for which this information is relevant.
    #[serde(rename = "round")]
    pub round: i32,
    #[serde(rename = "asset-holding", skip_serializing_if = "Option::is_none")]
    pub asset_holding: Option<serde_json::Value>,
    #[serde(rename = "created-asset", skip_serializing_if = "Option::is_none")]
    pub created_asset: Option<serde_json::Value>,
}



impl AccountAssetInformation200Response {
    /// Constructor for AccountAssetInformation200Response
    pub fn new(round: i32) -> AccountAssetInformation200Response {
        AccountAssetInformation200Response {
            round,
            asset_holding: None,
            created_asset: None,
        }
    }
}
