/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Application state delta.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountStateDelta {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "delta")]
    pub delta: Vec<serde_json::Value>,
}



impl AccountStateDelta {
    /// Constructor for AccountStateDelta
    pub fn new(address: String, delta: Vec<serde_json::Value>) -> AccountStateDelta {
        AccountStateDelta {
            address,
            delta,
        }
    }
}
