/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

use crate::models::AssetHolding;
use crate::models::AssetParams;

/// AccountAssetHolding describes the account's asset holding and asset parameters (if either exist) for a specific asset ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAssetHolding {
    #[serde(rename = "asset-holding")]
    pub asset_holding: AssetHolding,
    #[serde(rename = "asset-params", skip_serializing_if = "Option::is_none")]
    pub asset_params: Option<AssetParams>,
}

impl AlgorandMsgpack for AccountAssetHolding {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl AccountAssetHolding {
    /// Constructor for AccountAssetHolding
    pub fn new(asset_holding: AssetHolding) -> AccountAssetHolding {
        AccountAssetHolding {
            asset_holding,
            asset_params: None,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
