/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};




/// Participation ID of the submission
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddParticipationKey200Response {
        /// encoding of the participation ID.
    #[serde(rename = "partId")]
    pub part_id: String,
}



impl AlgorandMsgpack for AddParticipationKey200Response {
    const PREFIX: &'static [u8] = b"";  // Adjust prefix as needed for your specific type
}

impl AddParticipationKey200Response {
    /// Constructor for AddParticipationKey200Response
    pub fn new(part_id: String) -> AddParticipationKey200Response {
        AddParticipationKey200Response {
            part_id,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
