/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// An application's global/local/box state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationKvstorage {
        /// Key-Value pairs representing application states.
    #[serde(rename = "kvs")]
    pub kvs: Vec<serde_json::Value>,
        /// The address of the account associated with the local state.
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
}



impl ApplicationKvstorage {
    /// Constructor for ApplicationKvstorage
    pub fn new(kvs: Vec<serde_json::Value>) -> ApplicationKvstorage {
        ApplicationKvstorage {
            kvs,
            account: None,
        }
    }
}
