/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};






use crate::models::ApplicationKvstorage;

/// An application's initial global/local/box states that were accessed during simulation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationInitialStates {
        /// Application index.
    #[serde(rename = "id")]
    pub id: i32,
        /// An application's initial local states tied to different accounts.
    #[serde(rename = "app-locals", skip_serializing_if = "Option::is_none")]
    pub app_locals: Option<Vec<ApplicationKvstorage>>,
    #[serde(rename = "app-globals", skip_serializing_if = "Option::is_none")]
    pub app_globals: Option<ApplicationKvstorage>,
    #[serde(rename = "app-boxes", skip_serializing_if = "Option::is_none")]
    pub app_boxes: Option<ApplicationKvstorage>,
}




impl ApplicationInitialStates {
    /// Constructor for ApplicationInitialStates
    pub fn new(id: i32) -> ApplicationInitialStates {
        ApplicationInitialStates {
            id,
            app_locals: None,
            app_globals: None,
            app_boxes: None,
        }
    }

}
