/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Specifies maximums on the number of each type that may be stored.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationStateSchema {
        /// \[nui\] num of uints.
    #[serde(rename = "num-uint")]
    pub num_uint: i32,
        /// \[nbs\] num of byte slices.
    #[serde(rename = "num-byte-slice")]
    pub num_byte_slice: i32,
}



impl ApplicationStateSchema {
    /// Constructor for ApplicationStateSchema
    pub fn new(num_uint: i32, num_byte_slice: i32) -> ApplicationStateSchema {
        ApplicationStateSchema {
            num_uint,
            num_byte_slice,
        }
    }
}
