/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Stores local state associated with an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationLocalState {
        /// The application which this local state is for.
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "schema")]
    pub schema: serde_json::Value,
    #[serde(rename = "key-value", skip_serializing_if = "Option::is_none")]
    pub key_value: Option<Vec<serde_json::Value>>,
}



impl ApplicationLocalState {
    /// Constructor for ApplicationLocalState
    pub fn new(id: i32, schema: serde_json::Value) -> ApplicationLocalState {
        ApplicationLocalState {
            id,
            schema,
            key_value: None,
        }
    }
}
