/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};





/// References an account's local state for an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationLocalReference {
        /// Address of the account with the local state.
    #[serde(rename = "account")]
    pub account: String,
        /// Application ID of the local state application.
    #[serde(rename = "app")]
    pub app: i32,
}




impl ApplicationLocalReference {
    /// Constructor for ApplicationLocalReference
    pub fn new(account: String, app: i32) -> ApplicationLocalReference {
        ApplicationLocalReference {
            account,
            app,
        }
    }

}
