/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};




use crate::models::ApplicationParams;

/// Application index and its parameters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Application {
        /// \[appidx\] application index.
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "params")]
    pub params: ApplicationParams,
}




impl Application {
    /// Constructor for Application
    pub fn new(id: i32, params: ApplicationParams) -> Application {
        Application {
            id,
            params,
        }
    }

}
