/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Specifies both the unique identifier and the parameters for an asset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Asset {
        /// unique asset identifier
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "params")]
    pub params: serde_json::Value,
}



impl Asset {
    /// Constructor for Asset
    pub fn new(index: i32, params: serde_json::Value) -> Asset {
        Asset {
            index,
            params,
        }
    }
}
