/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

use crate::models::AssetParams;

/// Specifies both the unique identifier and the parameters for an asset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// unique asset identifier
    #[serde(rename = "index")]
    pub index: u64,
    #[serde(rename = "params")]
    pub params: AssetParams,
}

impl AlgorandMsgpack for Asset {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl Asset {
    /// Constructor for Asset
    pub fn new(index: u64, params: AssetParams) -> Asset {
        Asset { index, params }
    }

    /// Convenience method to get asset_id (alias for index field)
    /// This provides more consistent naming for tests and client code
    pub fn asset_id(&self) -> u64 {
        self.index
    }

    /// Convenience method to get total supply without nested params access
    /// This flattens the .params.total access pattern for better ergonomics
    pub fn total(&self) -> u64 {
        self.params.total
    }

    /// Convenience method to get decimals without nested params access
    pub fn decimals(&self) -> u64 {
        self.params.decimals
    }

    /// Convenience method to get unit name without nested params access
    pub fn unit_name(&self) -> Option<&String> {
        self.params.unit_name.as_ref()
    }

    /// Convenience method to get asset name without nested params access
    pub fn name(&self) -> Option<&String> {
        self.params.name.as_ref()
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
