/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};






/// Represents an AVM value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvmValue {
        /// value type. Value `1` refers to **bytes**, value `2` refers to **uint64**
    #[serde(rename = "type")]
    pub r#type: i32,
        /// bytes value.
    #[serde(rename = "bytes", skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
        /// uint value.
    #[serde(rename = "uint", skip_serializing_if = "Option::is_none")]
    pub uint: Option<i32>,
}




impl AvmValue {
    /// Constructor for AvmValue
    pub fn new(r#type: i32) -> AvmValue {
        AvmValue {
            r#type,
            bytes: None,
            uint: None,
        }
    }

}
