/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::serde_as;





/// References a box of an application.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoxReference {
        /// Application ID which this box belongs to
    #[serde(rename = "app")]
    pub app: i32,
        /// Base64 encoded box name
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "name")]
    pub name: Vec<u8>,
}




impl BoxReference {
    /// Constructor for BoxReference
    pub fn new(app: i32, name: Vec<u8>) -> BoxReference {
        BoxReference {
            app,
            name,
        }
    }

}
