/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

use crate::models::TealValue;

/// Stores the TEAL eval step data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DryrunState {
    /// Line number
    #[serde(rename = "line")]
    pub line: i32,
    /// Program counter
    #[serde(rename = "pc")]
    pub pc: i32,
    #[serde(rename = "stack")]
    pub stack: Vec<TealValue>,
    #[serde(rename = "scratch", skip_serializing_if = "Option::is_none")]
    pub scratch: Option<Vec<TealValue>>,
    /// Evaluation error if any
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl AlgorandMsgpack for DryrunState {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl DryrunState {
    /// Constructor for DryrunState
    pub fn new(line: i32, pc: i32, stack: Vec<TealValue>) -> DryrunState {
        DryrunState {
            line,
            pc,
            stack,
            scratch: None,
            error: None,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
