/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};

/// Request data type for dryrun endpoint. Given the Transactions and simulated ledger state upload, run TEAL scripts and return debugging information.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DryrunRequest {
    #[serde(rename = "txns")]
    pub txns: Vec<AlgokitSignedTransaction>,
    #[serde(rename = "accounts")]
    pub accounts: Vec<serde_json::Value>,
    #[serde(rename = "apps")]
    pub apps: Vec<serde_json::Value>,
        /// ProtocolVersion specifies a specific version string to operate under, otherwise whatever the current protocol of the network this algod is running in.
    #[serde(rename = "protocol-version")]
    pub protocol_version: String,
        /// Round is available to some TEAL scripts. Defaults to the current round on the network this algod is attached to.
    #[serde(rename = "round")]
    pub round: i32,
        /// LatestTimestamp is available to some TEAL scripts. Defaults to the latest confirmed timestamp this algod is attached to.
    #[serde(rename = "latest-timestamp")]
    pub latest_timestamp: i64,
    #[serde(rename = "sources")]
    pub sources: Vec<serde_json::Value>,
}

impl Default for DryrunRequest {
    fn default() -> Self {
        Self {
            txns: Vec::new(),
            accounts: Vec::new(),
            apps: Vec::new(),
            protocol_version: "".to_string(),
            round: 0,
            latest_timestamp: 0,
            sources: Vec::new(),
        }
    }
}


impl DryrunRequest {
    /// Constructor for DryrunRequest
    pub fn new(txns: Vec<AlgokitSignedTransaction>, accounts: Vec<serde_json::Value>, apps: Vec<serde_json::Value>, protocol_version: String, round: i32, latest_timestamp: i64, sources: Vec<serde_json::Value>) -> DryrunRequest {
        DryrunRequest {
            txns,
            accounts,
            apps,
            protocol_version,
            round,
            latest_timestamp,
            sources,
        }
    }
}
