/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};




/// Top level transaction IDs in a block.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockTxids200Response {
        /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    pub block_txids: Vec<String>,
}



impl AlgorandMsgpack for GetBlockTxids200Response {
    const PREFIX: &'static [u8] = b"";  // Adjust prefix as needed for your specific type
}

impl GetBlockTxids200Response {
    /// Constructor for GetBlockTxids200Response
    pub fn new(block_txids: Vec<String>) -> GetBlockTxids200Response {
        GetBlockTxids200Response {
            block_txids,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
