/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};





/// PendingTransactions is an array of signed transactions exactly as they were submitted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPendingTransactions200Response {
        /// An array of signed transaction objects.
    #[serde(rename = "top-transactions")]
    pub top_transactions: Vec<AlgokitSignedTransaction>,
        /// Total number of transactions in the pool.
    #[serde(rename = "total-transactions")]
    pub total_transactions: i32,
}



impl AlgorandMsgpack for GetPendingTransactions200Response {
    const PREFIX: &'static [u8] = b"";  // Adjust prefix as needed for your specific type
}

impl GetPendingTransactions200Response {
    /// Constructor for GetPendingTransactions200Response
    pub fn new(top_transactions: Vec<AlgokitSignedTransaction>, total_transactions: i32) -> GetPendingTransactions200Response {
        GetPendingTransactions200Response {
            top_transactions,
            total_transactions,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
