/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};

/// PendingTransactions is an array of signed transactions exactly as they were submitted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPendingTransactionsByAddress200Response {
        /// An array of signed transaction objects.
    #[serde(rename = "top-transactions")]
    pub top_transactions: Vec<AlgokitSignedTransaction>,
        /// Total number of transactions in the pool.
    #[serde(rename = "total-transactions")]
    pub total_transactions: i32,
}

impl Default for GetPendingTransactionsByAddress200Response {
    fn default() -> Self {
        Self {
            top_transactions: Vec::new(),
            total_transactions: 0,
        }
    }
}


impl GetPendingTransactionsByAddress200Response {
    /// Constructor for GetPendingTransactionsByAddress200Response
    pub fn new(top_transactions: Vec<AlgokitSignedTransaction>, total_transactions: i32) -> GetPendingTransactionsByAddress200Response {
        GetPendingTransactionsByAddress200Response {
            top_transactions,
            total_transactions,
        }
    }
}
