/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Box names of an application
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApplicationBoxes200Response {
    #[serde(rename = "boxes")]
    pub boxes: Vec<serde_json::Value>,
}



impl GetApplicationBoxes200Response {
    /// Constructor for GetApplicationBoxes200Response
    pub fn new(boxes: Vec<serde_json::Value>) -> GetApplicationBoxes200Response {
        GetApplicationBoxes200Response {
            boxes,
        }
    }
}
