/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};




/// Hash of a block header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockHash200Response {
        /// Block header hash.
    #[serde(rename = "blockHash")]
    pub block_hash: String,
}



impl AlgorandMsgpack for GetBlockHash200Response {
    const PREFIX: &'static [u8] = b"";  // Adjust prefix as needed for your specific type
}

impl GetBlockHash200Response {
    /// Constructor for GetBlockHash200Response
    pub fn new(block_hash: String) -> GetBlockHash200Response {
        GetBlockHash200Response {
            block_hash,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
