/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

/// Response containing the timestamp offset in seconds
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockTimeStampOffset200Response {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    pub offset: i32,
}

impl AlgorandMsgpack for GetBlockTimeStampOffset200Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl GetBlockTimeStampOffset200Response {
    /// Constructor for GetBlockTimeStampOffset200Response
    pub fn new(offset: i32) -> GetBlockTimeStampOffset200Response {
        GetBlockTimeStampOffset200Response { offset }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
