/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// All logs emitted in the given round. Each app call, whether top-level or inner, that contains logs results in a separate AppCallLogs object. Therefore there may be multiple AppCallLogs with the same application ID and outer transaction ID in the event of multiple inner app calls to the same app. App calls with no logs are not included in the response. AppCallLogs are returned in the same order that their corresponding app call appeared in the block (pre-order traversal of inner app calls)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockLogs200Response {
    #[serde(rename = "logs")]
    pub logs: Vec<serde_json::Value>,
}



impl GetBlockLogs200Response {
    /// Constructor for GetBlockLogs200Response
    pub fn new(logs: Vec<serde_json::Value>) -> GetBlockLogs200Response {
        GetBlockLogs200Response {
            logs,
        }
    }
}
