/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Top level transaction IDs in a block.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockTxids200Response {
        /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    pub block_txids: Vec<String>,
}



impl GetBlockTxids200Response {
    /// Constructor for GetBlockTxids200Response
    pub fn new(block_txids: Vec<String>) -> GetBlockTxids200Response {
        GetBlockTxids200Response {
            block_txids,
        }
    }
}
