/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Hash of a block header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockHash200Response {
        /// Block header hash.
    #[serde(rename = "blockHash")]
    pub block_hash: String,
}



impl GetBlockHash200Response {
    /// Constructor for GetBlockHash200Response
    pub fn new(block_hash: String) -> GetBlockHash200Response {
        GetBlockHash200Response {
            block_hash,
        }
    }
}
