/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

use crate::models::BoxDescriptor;

/// Box names of an application
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApplicationBoxes200Response {
    #[serde(rename = "boxes")]
    pub boxes: Vec<BoxDescriptor>,
}

impl AlgorandMsgpack for GetApplicationBoxes200Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl GetApplicationBoxes200Response {
    /// Constructor for GetApplicationBoxes200Response
    pub fn new(boxes: Vec<BoxDescriptor>) -> GetApplicationBoxes200Response {
        GetApplicationBoxes200Response { boxes }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
