/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

/// Supply represents the current supply of MicroAlgos in the system
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSupply200Response {
    /// Round
    #[serde(rename = "current_round")]
    pub current_round: i32,
    /// OnlineMoney
    #[serde(rename = "online-money")]
    pub online_money: i32,
    /// TotalMoney
    #[serde(rename = "total-money")]
    pub total_money: i32,
}

impl AlgorandMsgpack for GetSupply200Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl GetSupply200Response {
    /// Constructor for GetSupply200Response
    pub fn new(current_round: i32, online_money: i32, total_money: i32) -> GetSupply200Response {
        GetSupply200Response {
            current_round,
            online_money,
            total_money,
        }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
