/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::LedgerStateDeltaForTransactionGroup;

/// Response containing all ledger state deltas for transaction groups, with their associated Ids, in a single round.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionGroupLedgerStateDeltasForRound {
    #[serde(rename = "Deltas")]
    pub deltas: Vec<LedgerStateDeltaForTransactionGroup>,
}

impl GetTransactionGroupLedgerStateDeltasForRound {
    /// Constructor for GetTransactionGroupLedgerStateDeltasForRound
    pub fn new(
        deltas: Vec<LedgerStateDeltaForTransactionGroup>,
    ) -> GetTransactionGroupLedgerStateDeltasForRound {
        GetTransactionGroupLedgerStateDeltasForRound { deltas }
    }
}
