/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Response containing all ledger state deltas for transaction groups, with their associated Ids, in a single round.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionGroupLedgerStateDeltasForRound200Response {
    #[serde(rename = "Deltas")]
    pub deltas: Vec<serde_json::Value>,
}



impl GetTransactionGroupLedgerStateDeltasForRound200Response {
    /// Constructor for GetTransactionGroupLedgerStateDeltasForRound200Response
    pub fn new(deltas: Vec<serde_json::Value>) -> GetTransactionGroupLedgerStateDeltasForRound200Response {
        GetTransactionGroupLedgerStateDeltasForRound200Response {
            deltas,
        }
    }
}
