/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Contains a ledger delta for a single transaction group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LedgerStateDeltaForTransactionGroup {
    #[serde(rename = "Delta")]
    pub delta: serde_json::Value,
    #[serde(rename = "Ids")]
    pub ids: Vec<String>,
}



impl LedgerStateDeltaForTransactionGroup {
    /// Constructor for LedgerStateDeltaForTransactionGroup
    pub fn new(delta: serde_json::Value, ids: Vec<String>) -> LedgerStateDeltaForTransactionGroup {
        LedgerStateDeltaForTransactionGroup {
            delta,
            ids,
        }
    }
}
