/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};



/// Ledger StateDelta object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LedgerStateDelta {
}




impl LedgerStateDelta {
    /// Default constructor for LedgerStateDelta
    pub fn new() -> LedgerStateDelta {
        LedgerStateDelta::default()
    }

}
