/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

/// Transaction ID of the submission.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RawTransaction200Response {
    /// encoding of the transaction hash.
    #[serde(rename = "txId")]
    pub tx_id: String,
}

impl AlgorandMsgpack for RawTransaction200Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl RawTransaction200Response {
    /// Constructor for RawTransaction200Response
    pub fn new(tx_id: String) -> RawTransaction200Response {
        RawTransaction200Response { tx_id }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
