/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};




use crate::models::AvmValue;

/// A write operation into a scratch slot.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScratchChange {
        /// The scratch slot written.
    #[serde(rename = "slot")]
    pub slot: i32,
    #[serde(rename = "new-value")]
    pub new_value: AvmValue,
}




impl ScratchChange {
    /// Constructor for ScratchChange
    pub fn new(slot: i32, new_value: AvmValue) -> ScratchChange {
        ScratchChange {
            slot,
            new_value,
        }
    }

}
