/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// A write operation into a scratch slot.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScratchChange {
        /// The scratch slot written.
    #[serde(rename = "slot")]
    pub slot: i32,
    #[serde(rename = "new-value")]
    pub new_value: serde_json::Value,
}



impl ScratchChange {
    /// Constructor for ScratchChange
    pub fn new(slot: i32, new_value: serde_json::Value) -> ScratchChange {
        ScratchChange {
            slot,
            new_value,
        }
    }
}
