/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use algokit_transact::{SignedTransaction as AlgokitSignedTransaction, AlgorandMsgpack};

/// A transaction group to simulate.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateRequestTransactionGroup {
        /// An atomic transaction group.
    #[serde(rename = "txns")]
    pub txns: Vec<AlgokitSignedTransaction>,
}

impl Default for SimulateRequestTransactionGroup {
    fn default() -> Self {
        Self {
            txns: Vec::new(),
        }
    }
}


impl SimulateRequestTransactionGroup {
    /// Constructor for SimulateRequestTransactionGroup
    pub fn new(txns: Vec<AlgokitSignedTransaction>) -> SimulateRequestTransactionGroup {
        SimulateRequestTransactionGroup {
            txns,
        }
    }
}
