/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Result of a transaction group simulation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateTransaction200Response {
        /// The version of this response object.
    #[serde(rename = "version")]
    pub version: i32,
        /// The round immediately preceding this simulation. State changes through this round were used to run this simulation.
    #[serde(rename = "last-round")]
    pub last_round: i32,
        /// A result object for each transaction group that was simulated.
    #[serde(rename = "txn-groups")]
    pub txn_groups: Vec<serde_json::Value>,
    #[serde(rename = "eval-overrides", skip_serializing_if = "Option::is_none")]
    pub eval_overrides: Option<serde_json::Value>,
    #[serde(rename = "exec-trace-config", skip_serializing_if = "Option::is_none")]
    pub exec_trace_config: Option<serde_json::Value>,
    #[serde(rename = "initial-states", skip_serializing_if = "Option::is_none")]
    pub initial_states: Option<serde_json::Value>,
}



impl SimulateTransaction200Response {
    /// Constructor for SimulateTransaction200Response
    pub fn new(version: i32, last_round: i32, txn_groups: Vec<serde_json::Value>) -> SimulateTransaction200Response {
        SimulateTransaction200Response {
            version,
            last_round,
            txn_groups,
            eval_overrides: None,
            exec_trace_config: None,
            initial_states: None,
        }
    }
}
