/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

/// An catchpoint start response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartCatchup201Response {
    /// Catchup start response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl AlgorandMsgpack for StartCatchup201Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl StartCatchup201Response {
    /// Constructor for StartCatchup201Response
    pub fn new(catchup_message: String) -> StartCatchup201Response {
        StartCatchup201Response { catchup_message }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
