/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Application state delta.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateDelta {
}



impl StateDelta {
    /// Default constructor for StateDelta
    pub fn new() -> StateDelta {
        StateDelta::default()
    }
}
