/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Represents a TEAL value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealValue {
    /// \[tt\] value type. Value `1` refers to **bytes**, value `2` refers to **uint**
    #[serde(rename = "type")]
    pub r#type: i32,
    /// \[tb\] bytes value.
    #[serde(rename = "bytes")]
    pub bytes: String,
    /// \[ui\] uint value.
    #[serde(rename = "uint")]
    pub uint: i32,
}

impl TealValue {
    /// Constructor for TealValue
    pub fn new(r#type: i32, bytes: String, uint: i32) -> TealValue {
        TealValue {
            r#type,
            bytes,
            uint,
        }
    }
}
