/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DryrunResponse contains per-txn debug information from a dryrun.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealDryrun200Response {
    #[serde(rename = "txns")]
    pub txns: Vec<serde_json::Value>,
    #[serde(rename = "error")]
    pub error: String,
        /// Protocol version is the protocol version Dryrun was operated under.
    #[serde(rename = "protocol-version")]
    pub protocol_version: String,
}



impl TealDryrun200Response {
    /// Constructor for TealDryrun200Response
    pub fn new(txns: Vec<serde_json::Value>, error: String, protocol_version: String) -> TealDryrun200Response {
        TealDryrun200Response {
            txns,
            error,
            protocol_version,
        }
    }
}
