/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};

/// Teal disassembly Result
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealDisassemble200Response {
    /// disassembled Teal code
    #[serde(rename = "result")]
    pub result: String,
}

impl AlgorandMsgpack for TealDisassemble200Response {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl TealDisassemble200Response {
    /// Constructor for TealDisassemble200Response
    pub fn new(result: String) -> TealDisassemble200Response {
        TealDisassemble200Response { result }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
