/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};



/// Represents a key-value store for use in an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealKeyValueStore {
}




impl TealKeyValueStore {
    /// Default constructor for TealKeyValueStore
    pub fn new() -> TealKeyValueStore {
        TealKeyValueStore::default()
    }

}
