/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::TealValue;

/// Represents a key-value pair in an application store.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealKeyValue {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: TealValue,
}

impl TealKeyValue {
    /// Constructor for TealKeyValue
    pub fn new(key: String, value: TealValue) -> TealKeyValue {
        TealKeyValue { key, value }
    }
}
