// Auto-generated: map of model name -> array of camelCase field names that are bytes (Uint8Array) in domain
export const BYTES_FIELDS: Record<string, readonly string[]> = {
  AccountParticipation: ['selectionParticipationKey', 'voteParticipationKey', 'stateProofKey'],
  TealValue: ['bytes'],
  ApplicationParams: ['approvalProgram', 'clearStateProgram'],
  AssetParams: ['metadataHash', 'nameB64', 'unitNameB64', 'urlB64'],
  Block: [
    'genesisHash',
    'previousBlockHash',
    'previousBlockHash512',
    'seed',
    'transactionsRoot',
    'transactionsRootSha256',
    'transactionsRootSha512',
  ],
  Box: ['name', 'value'],
  BoxDescriptor: ['name'],
  BoxReference: ['name'],
  Transaction: ['genesisHash', 'group', 'lease', 'note'],
  TransactionApplication: ['approvalProgram', 'clearStateProgram'],
  TransactionHeartbeat: ['hbSeed', 'hbVoteId'],
  TransactionKeyreg: ['selectionParticipationKey', 'voteParticipationKey', 'stateProofKey'],
  TransactionSignature: ['sig'],
  TransactionSignatureLogicsig: ['logic', 'signature'],
  TransactionSignatureMultisigSubsignature: ['publicKey', 'signature'],
  StateProofFields: ['sigCommit'],
  HbProofFields: ['hbSig', 'hbPk', 'hbPk2', 'hbPk1sig', 'hbPk2sig'],
  IndexerStateProofMessage: ['blockHeadersCommitment', 'votersCommitment'],
  StateProofSignature: ['falconSignature', 'verifyingKey'],
  StateProofVerifier: ['commitment'],
  StateProofTracking: ['votersCommitment'],
}
