/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

// Consolidated client
pub mod client;

// Parameter enums for type-safe API parameters
pub mod parameter_enums;

// Individual endpoint modules
pub mod lookup_account_app_local_states;
pub mod lookup_account_assets;
pub mod lookup_account_by_id;
pub mod lookup_account_created_applications;
pub mod lookup_account_created_assets;
pub mod lookup_account_transactions;
pub mod lookup_application_box_by_id_and_name;
pub mod lookup_application_by_id;
pub mod lookup_application_logs_by_id;
pub mod lookup_asset_balances;
pub mod lookup_asset_by_id;
pub mod lookup_asset_transactions;
pub mod lookup_block;
pub mod lookup_transaction;
pub mod make_health_check;
pub mod search_for_accounts;
pub mod search_for_application_boxes;
pub mod search_for_applications;
pub mod search_for_assets;
pub mod search_for_block_headers;
pub mod search_for_transactions;

/// Unified error type that can represent any API error from any endpoint
#[derive(Debug, thiserror::Error)]
pub enum AlgodApiError {
    #[error("Make_health_check error: {0:?}")]
    MakeHealthCheck(make_health_check::MakeHealthCheckError),
    #[error("Search_for_accounts error: {0:?}")]
    SearchForAccounts(search_for_accounts::SearchForAccountsError),
    #[error("Lookup_account_by_id error: {0:?}")]
    LookupAccountById(lookup_account_by_id::LookupAccountByIdError),
    #[error("Lookup_account_assets error: {0:?}")]
    LookupAccountAssets(lookup_account_assets::LookupAccountAssetsError),
    #[error("Lookup_account_created_assets error: {0:?}")]
    LookupAccountCreatedAssets(lookup_account_created_assets::LookupAccountCreatedAssetsError),
    #[error("Lookup_account_app_local_states error: {0:?}")]
    LookupAccountAppLocalStates(lookup_account_app_local_states::LookupAccountAppLocalStatesError),
    #[error("Lookup_account_created_applications error: {0:?}")]
    LookupAccountCreatedApplications(
        lookup_account_created_applications::LookupAccountCreatedApplicationsError,
    ),
    #[error("Lookup_account_transactions error: {0:?}")]
    LookupAccountTransactions(lookup_account_transactions::LookupAccountTransactionsError),
    #[error("Search_for_applications error: {0:?}")]
    SearchForApplications(search_for_applications::SearchForApplicationsError),
    #[error("Lookup_application_by_id error: {0:?}")]
    LookupApplicationById(lookup_application_by_id::LookupApplicationByIdError),
    #[error("Search_for_application_boxes error: {0:?}")]
    SearchForApplicationBoxes(search_for_application_boxes::SearchForApplicationBoxesError),
    #[error("Lookup_application_box_by_id_and_name error: {0:?}")]
    LookupApplicationBoxByIdAndName(
        lookup_application_box_by_id_and_name::LookupApplicationBoxByIdAndNameError,
    ),
    #[error("Lookup_application_logs_by_id error: {0:?}")]
    LookupApplicationLogsById(lookup_application_logs_by_id::LookupApplicationLogsByIdError),
    #[error("Search_for_assets error: {0:?}")]
    SearchForAssets(search_for_assets::SearchForAssetsError),
    #[error("Lookup_asset_by_id error: {0:?}")]
    LookupAssetById(lookup_asset_by_id::LookupAssetByIdError),
    #[error("Lookup_asset_balances error: {0:?}")]
    LookupAssetBalances(lookup_asset_balances::LookupAssetBalancesError),
    #[error("Lookup_asset_transactions error: {0:?}")]
    LookupAssetTransactions(lookup_asset_transactions::LookupAssetTransactionsError),
    #[error("Search_for_block_headers error: {0:?}")]
    SearchForBlockHeaders(search_for_block_headers::SearchForBlockHeadersError),
    #[error("Lookup_block error: {0:?}")]
    LookupBlock(lookup_block::LookupBlockError),
    #[error("Lookup_transaction error: {0:?}")]
    LookupTransaction(lookup_transaction::LookupTransactionError),
    #[error("Search_for_transactions error: {0:?}")]
    SearchForTransactions(search_for_transactions::SearchForTransactionsError),
    #[error("Unknown API error: {0}")]
    Unknown(String),
}

impl From<make_health_check::MakeHealthCheckError> for AlgodApiError {
    fn from(err: make_health_check::MakeHealthCheckError) -> Self {
        AlgodApiError::MakeHealthCheck(err)
    }
}

impl From<search_for_accounts::SearchForAccountsError> for AlgodApiError {
    fn from(err: search_for_accounts::SearchForAccountsError) -> Self {
        AlgodApiError::SearchForAccounts(err)
    }
}

impl From<lookup_account_by_id::LookupAccountByIdError> for AlgodApiError {
    fn from(err: lookup_account_by_id::LookupAccountByIdError) -> Self {
        AlgodApiError::LookupAccountById(err)
    }
}

impl From<lookup_account_assets::LookupAccountAssetsError> for AlgodApiError {
    fn from(err: lookup_account_assets::LookupAccountAssetsError) -> Self {
        AlgodApiError::LookupAccountAssets(err)
    }
}

impl From<lookup_account_created_assets::LookupAccountCreatedAssetsError> for AlgodApiError {
    fn from(err: lookup_account_created_assets::LookupAccountCreatedAssetsError) -> Self {
        AlgodApiError::LookupAccountCreatedAssets(err)
    }
}

impl From<lookup_account_app_local_states::LookupAccountAppLocalStatesError> for AlgodApiError {
    fn from(err: lookup_account_app_local_states::LookupAccountAppLocalStatesError) -> Self {
        AlgodApiError::LookupAccountAppLocalStates(err)
    }
}

impl From<lookup_account_created_applications::LookupAccountCreatedApplicationsError>
    for AlgodApiError
{
    fn from(
        err: lookup_account_created_applications::LookupAccountCreatedApplicationsError,
    ) -> Self {
        AlgodApiError::LookupAccountCreatedApplications(err)
    }
}

impl From<lookup_account_transactions::LookupAccountTransactionsError> for AlgodApiError {
    fn from(err: lookup_account_transactions::LookupAccountTransactionsError) -> Self {
        AlgodApiError::LookupAccountTransactions(err)
    }
}

impl From<search_for_applications::SearchForApplicationsError> for AlgodApiError {
    fn from(err: search_for_applications::SearchForApplicationsError) -> Self {
        AlgodApiError::SearchForApplications(err)
    }
}

impl From<lookup_application_by_id::LookupApplicationByIdError> for AlgodApiError {
    fn from(err: lookup_application_by_id::LookupApplicationByIdError) -> Self {
        AlgodApiError::LookupApplicationById(err)
    }
}

impl From<search_for_application_boxes::SearchForApplicationBoxesError> for AlgodApiError {
    fn from(err: search_for_application_boxes::SearchForApplicationBoxesError) -> Self {
        AlgodApiError::SearchForApplicationBoxes(err)
    }
}

impl From<lookup_application_box_by_id_and_name::LookupApplicationBoxByIdAndNameError>
    for AlgodApiError
{
    fn from(
        err: lookup_application_box_by_id_and_name::LookupApplicationBoxByIdAndNameError,
    ) -> Self {
        AlgodApiError::LookupApplicationBoxByIdAndName(err)
    }
}

impl From<lookup_application_logs_by_id::LookupApplicationLogsByIdError> for AlgodApiError {
    fn from(err: lookup_application_logs_by_id::LookupApplicationLogsByIdError) -> Self {
        AlgodApiError::LookupApplicationLogsById(err)
    }
}

impl From<search_for_assets::SearchForAssetsError> for AlgodApiError {
    fn from(err: search_for_assets::SearchForAssetsError) -> Self {
        AlgodApiError::SearchForAssets(err)
    }
}

impl From<lookup_asset_by_id::LookupAssetByIdError> for AlgodApiError {
    fn from(err: lookup_asset_by_id::LookupAssetByIdError) -> Self {
        AlgodApiError::LookupAssetById(err)
    }
}

impl From<lookup_asset_balances::LookupAssetBalancesError> for AlgodApiError {
    fn from(err: lookup_asset_balances::LookupAssetBalancesError) -> Self {
        AlgodApiError::LookupAssetBalances(err)
    }
}

impl From<lookup_asset_transactions::LookupAssetTransactionsError> for AlgodApiError {
    fn from(err: lookup_asset_transactions::LookupAssetTransactionsError) -> Self {
        AlgodApiError::LookupAssetTransactions(err)
    }
}

impl From<search_for_block_headers::SearchForBlockHeadersError> for AlgodApiError {
    fn from(err: search_for_block_headers::SearchForBlockHeadersError) -> Self {
        AlgodApiError::SearchForBlockHeaders(err)
    }
}

impl From<lookup_block::LookupBlockError> for AlgodApiError {
    fn from(err: lookup_block::LookupBlockError) -> Self {
        AlgodApiError::LookupBlock(err)
    }
}

impl From<lookup_transaction::LookupTransactionError> for AlgodApiError {
    fn from(err: lookup_transaction::LookupTransactionError) -> Self {
        AlgodApiError::LookupTransaction(err)
    }
}

impl From<search_for_transactions::SearchForTransactionsError> for AlgodApiError {
    fn from(err: search_for_transactions::SearchForTransactionsError) -> Self {
        AlgodApiError::SearchForTransactions(err)
    }
}

/// The main error type for all algod client operations
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("HTTP error: {0}")]
    Http(#[from] algokit_http_client::HttpError),
    #[error("Serialization error: {0}")]
    Serde(String),
    #[error("API error: {0}")]
    Api(#[from] AlgodApiError),
}

#[derive(Debug, PartialEq, Eq)]
pub enum ContentType {
    Json,
    MsgPack,
    Text,
    Unsupported(String),
}

impl From<&str> for ContentType {
    fn from(content_type: &str) -> Self {
        if content_type.contains("application/json") {
            ContentType::Json
        } else if content_type.contains("application/msgpack") {
            ContentType::MsgPack
        } else if content_type.contains("text/plain") {
            ContentType::Text
        } else {
            ContentType::Unsupported(content_type.to_string())
        }
    }
}

pub fn urlencode<T: AsRef<str>>(s: T) -> String {
    ::url::form_urlencoded::byte_serialize(s.as_ref().as_bytes()).collect()
}

// Re-export the consolidated client
pub use client::AlgodClient;

// Re-export parameter enums
pub use parameter_enums::*;

// Re-export all endpoint functions
pub use lookup_account_app_local_states::{
    LookupAccountAppLocalStatesError, lookup_account_app_local_states,
};
pub use lookup_account_assets::{LookupAccountAssetsError, lookup_account_assets};
pub use lookup_account_by_id::{LookupAccountByIdError, lookup_account_by_id};
pub use lookup_account_created_applications::{
    LookupAccountCreatedApplicationsError, lookup_account_created_applications,
};
pub use lookup_account_created_assets::{
    LookupAccountCreatedAssetsError, lookup_account_created_assets,
};
pub use lookup_account_transactions::{
    LookupAccountTransactionsError, lookup_account_transactions,
};
pub use lookup_application_box_by_id_and_name::{
    LookupApplicationBoxByIdAndNameError, lookup_application_box_by_id_and_name,
};
pub use lookup_application_by_id::{LookupApplicationByIdError, lookup_application_by_id};
pub use lookup_application_logs_by_id::{
    LookupApplicationLogsByIdError, lookup_application_logs_by_id,
};
pub use lookup_asset_balances::{LookupAssetBalancesError, lookup_asset_balances};
pub use lookup_asset_by_id::{LookupAssetByIdError, lookup_asset_by_id};
pub use lookup_asset_transactions::{LookupAssetTransactionsError, lookup_asset_transactions};
pub use lookup_block::{LookupBlockError, lookup_block};
pub use lookup_transaction::{LookupTransactionError, lookup_transaction};
pub use make_health_check::{MakeHealthCheckError, make_health_check};
pub use search_for_accounts::{SearchForAccountsError, search_for_accounts};
pub use search_for_application_boxes::{
    SearchForApplicationBoxesError, search_for_application_boxes,
};
pub use search_for_applications::{SearchForApplicationsError, search_for_applications};
pub use search_for_assets::{SearchForAssetsError, search_for_assets};
pub use search_for_block_headers::{SearchForBlockHeadersError, search_for_block_headers};
pub use search_for_transactions::{SearchForTransactionsError, search_for_transactions};
